redhat-developer/yaml-language-server

- src/languageService/parser/jsonParser.ts
- src/languageService/parser/yamlParser.ts
- Removed isBoolean from jsonParser because its no longer needed.
- yamlParser now turns on, off etc etc into boolean nodes.
- isBoolean now puts true, false, True, False, TRUE, FALSE first as they are the most commonly used.
> Removed isBoolean from jsonParser and moved it to yamlParser

- src/languageService/jsonSchema.ts
- src/languageService/kubernetesTransformer.ts
- src/languageService/parser/jsonParser.ts
- test/integration.test.ts
Reverted regression from 2a8456a7e2e319aece0f9d05e5af087450cedf63 in jsonParser testAlternatives.
Reason: Kubernetes schema validation was correct according to the schema and didn't need to change.
> DO NOT MERGE: Reverted regression in jsonParser testAlternatives

- src/server.ts
This PR gets json schemas from the json schema store api [catalog endpoint](http://schemastore.org/api/json/catalog.json).
The question is whether we want to have this intergrated as a feature, especially if we can't verify the quality of the yaml files on the json schema store.
> Pull json schemas from json schema store for well known yaml files

- package.json
As Mocha is only used for testing and not for the actual execution of the language server, it should be listed in the `devDependencies` section of the package.json file instead of the `dependencies` section.
> Mocha should be a dev dependency and not a regular dependency

- test/uri.test.ts
I've changed the URI tests to use `path.sep` for the separator character so that the tests will be cross-platform.
This fixes #30.
> Change URI tests to be cross-platform

- src/languageService/parser/yamlParser.ts
- test/schemaValidation.test.ts
Implemented include ref to return a string ast node and added two new tests for this functionality.
> Fix for redhat-developer/vscode-yaml#52

- src/languageService/yamlLanguageService.ts
- src/server.ts
This fix allows the custom language service to use reset schema. Combined with https://github.com/redhat-developer/vscode-yaml/pull/53. It will make it so modified json files are reloaded when editing.
> Fix for redhat-developer/yaml-language-server#34

- README.md
- src/server.ts
This commit lets an end user specify something like
"yaml.schemas": {
"kedge": "globPattern"
},
in their VS Code user settings, and it expands the keyword "kedge"
to the location of the Kedge JSON Schema, hence enabling the
auto-completion and syntax validation goodness for Kedge in the
yaml-language-server itself.
Also adds docs.
> Allow replacing "kedge" keyword to JSON Schema URL

- src/languageService/parser/jsonParser.ts
This fix follows http://yaml.org/type/merge.html on the cases when you have "<<" followed by an object node or a sequence node.
> Fixed redhat-developer/vscode-yaml#60

- package-lock.json
- package.json
The dependency to `deep-equal` was originally added in 43ad74318733836099bc11111d4099890a7b9075 but was then removed in a66bb66b466ccee95f49100c4c351d3d457deb89 during the 0.0.2 release. It remains unused and can be removed from the package.json file.
> Remove unused dependency to deep-equal

- src/languageservice/services/jsonSchemaService.ts
- test/schema.test.ts
Promise-based code is meant to be chained. Instead of returning `null` for an asynchronous function, returning a promise that resolves to `null` would be more intuitive and easier to handle for clients.
> Return promises that resolve to null

- src/server.ts
Use textDocument.formatting.dynamicRegistration to check whether formatting
supports dynamic registration.
Fixes #74
> Correct capability for checking formatting dynamic registration

- src/languageservice/services/jsonSchemaService.ts
- src/languageservice/utils/strings.ts
- test/strings.test.ts
e.g. case-insensitive pattern
```yaml
yaml.schemas: {
"kubernetes": "/myYamlFile\\.yaml/i"
}
```
> support associate schemas with files in a regular expression

- package-lock.json
- package.json
- src/languageservice/services/yamlFormatter.ts
- src/languageservice/yamlLanguageService.ts
- src/server.ts
- test/formatter.test.ts
This PR introduces the YAML formatter from [prettier](https://prettier.io). The prettier yaml formatter makes use of a different parser that allows comments in YAML and is pretty heavily maintained.
> Added the formatter from prettier

- src/languageservice/services/jsonSchemaService.ts
- src/languageservice/yamlLanguageService.ts
- src/server.ts
This PR makes the custom schema provider feature needed to be registered in order to use. This occurs because some clients supporting LSP do not handle the case when a server sends a CustomSchemaRequest to the client and thus shows an error/does not allow them to use it.
See: https://github.com/redhat-developer/yaml-language-server/issues/56 and https://github.com/redhat-developer/yaml-language-server/issues/83
@andxu Can you review because it effects previous your work
VSCode-YAML side is here: https://github.com/redhat-developer/vscode-yaml/pull/121
> Added registration for custom schema provider

- src/server.ts
Also moved "setting.yaml" existence check in one if block.
This fixes a problem that `yaml.format.bracketSpacing` is unable to be set to false.
> Enable to set bracketSpacing option to false

- src/server.ts
This PR fixes https://github.com/redhat-developer/yaml-language-server/issues/111 by checking to see if the settings.yaml.format was defined before trying to set settings.yaml.format.singleQuote etc.
> Validate settings.yaml.format before setting

- README.md
- src/languageservice/parser/yamlParser.ts
- src/languageservice/services/yamlCompletion.ts
- src/languageservice/utils/arrUtils.ts
Previously there wasn't much validation around custom tags that were being inserted into the parser. Without the validation, you could easily crash the language server by providing an invalid custom tag type. This PR fixes that issues and introduces changes to the README to make custom tag use more clear.
> Fixed issue with custom tags that can crash the language server

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion3.test.ts
This is a limitation imposed by the language server protocol. Doing otherwise will make some language protocol clients, such as VS Code, reject the completions. VS Code prints the following in the developer tools console for if you try and give it a multi-line `CompletionItem.textEdit`: `INVALID text edit -> must be single line and on the same line`, and it ignores all such completions, leading to it offering the default word completions instead.
See [LSP Spec - textDocument/completion](https://microsoft.github.io/language-server-protocol/specification#textDocument_completion):
```ts
/**
* An edit which is applied to a document when selecting this completion. When an edit is provided the value of
* `insertText` is ignored.
*
* *Note:* The range of the edit must be a single line range and …
```
> Only set CompletionItem.textEdit if it encompasses a single line

- src/languageservice/yamlLanguageService.ts
- src/server.ts
- test/formatter.test.ts
Adds printWidth setting so that users can specify what happens on format when their text goes over a certain length.
Fixes: https://github.com/redhat-developer/yaml-language-server/issues/117 and https://github.com/redhat-developer/vscode-yaml/issues/88
> Added printWidth setting

- bin/yaml-language-server
- package.json
Related in https://github.com/redhat-developer/yaml-language-server/pull/98
Make `yaml-launguage-server` command executable format.
(I referred to the [tsserver](https://github.com/Microsoft/TypeScript/blob/f776bead4f1c28f375bf2f7676a277a47745bb48/bin/tsserver) command)
With this, we can execute as follows.
```
$ npm i -g yaml-language-server
$ yaml-language-server --stdio
```
> Make `yaml-launguage-server` command executable format

- src/languageservice/services/yamlFormatter.ts
- src/languageservice/yamlLanguageService.ts
- src/server.ts
- test/formatter.test.ts
This PR fixes the formatter so that it respects the yaml.format.enable setting.
> Fix formatter

- src/server.ts
Unfortunately adding the trigger characters made it so that in a few cases the autocompletion was recommending completion items that would end up causing errors. In order to maintain user experience, I am reverting this PR.
View: https://github.com/redhat-developer/yaml-language-server/issues/129 for more info.
Reverts redhat-developer/yaml-language-server#127
> Revert "Added trigger characters"

- src/server.ts
This seems to fix https://github.com/redhat-developer/yaml-language-server/issues/58 for me.
Is the fix that straightforward, or is there something I'm missing? Thanks!
> Update kube schema url to v1.14.0

- package-lock.json
- package.json
- src/languageservice/services/yamlFormatter.ts
This PR makes prettier an optional dependency because prettier does not play well with webpack.
> Make prettier an optional dependency since it doesn't work with webpack

- src/server.ts
Running `yaml-language-server` with the `vscode-yaml` extension keeps giving warnings in the editor, such as this one:
```
Extension 'redhat.vscode-yaml' uses a document selector without scheme. Learn more about this: https://go.microsoft.com/fwlink/?linkid=872305
```
Adding in the 'file' and 'untitled' schemes should keep it working with all files but now without the warnings.
> Use document selector schemes in formatter registration

- src/languageservice/parser/jsonParser04.ts
- src/languageservice/parser/jsonParser07.ts
- test/autoCompletion.test.ts
- test/schemaValidation.test.ts
This PR solves two issues:
1. Autocomplete will now work on a value when there are multiple enums available.
Previously it wouldn't show anything when we have something like this as a subschema:
```
{
"kind": {
"type": "string",
"enum": [
"Test1",
"Test2"
]
}
}
}
```
and tried to autocomplete on kind.
2. It will show the correct validation when a key has an associated null value.
Previously when you had:
```
kind: 
```
and looked at the problems you would get an error saying something like
``` 
Value is not accepted. Valid values: "MutatingWebhookConfiguration" 
```
With this change you will now get 
```
Value is not accepted. Valid values: "MutatingWebhookConfiguration", "MutatingWebhookConfigurationList", "ValidatingWebhookConfiguration", …
```
> Fix for validation with multiple enums 

- src/server.ts
This PR disables the document range formatting explicitly in the initializeResult.
Related issues:
https://github.com/redhat-developer/vscode-yaml/issues/220
> Disable document range formatting

- package-lock.json
- src/languageservice/services/documentSymbols.ts
- src/languageservice/services/jsonSchemaService.ts
- src/languageservice/services/yamlHover.ts
- src/languageservice/services/yamlValidation.ts
- src/languageservice/yamlLanguageService.ts
This is a WIP PR that seeks to fix the issues with the registerContributor API. As far as I can see the only way we can trigger https://github.com/redhat-developer/yaml-language-server/blob/master/src/languageservice/services/schemaRequestHandler.ts#L68 from inside of the json language service is to call jsonLanguageService.configure() before we actually handle the hover and validation requests.
Hover and validation are the only requests that would need this as auto completion still uses code inside of the project, rather than delegating to the json language service, and document symbols does not need a schema.
> WIP - Fixing issue with registerContributor API

- src/server.ts
This PR catches the case when a user sets a proxy and the schema store schemas cannot be resolved. Previously it was throwing an error that was uncaught.
Related issues:
https://github.com/redhat-developer/yaml-language-server/issues/182
https://github.com/redhat-developer/vscode-yaml/issues/127
> Catch errors that come from trying to resolve schema store schemas

- src/server.ts
Use textDocument.rangeFormatting.dynamicRegistration instead of
workspace.symbol.dynamicRegistration.
Similar issue for VSCode JSON Language Server.
https://github.com/microsoft/vscode/issues/81592
> Correct capability to check rangeFormatting dynamic registration

- src/server.ts
For #192.
Clients need not specify textDocument or workspace capabilities when initializing ([spec](https://github.com/microsoft/language-server-protocol/blame/gh-pages/_specifications/specification-3-14.md#L1554)).
This PR handles these potentially absent values with ~~an existence check and a touch of destructuring and default values~~ really long existence check chains.
> Handle less-specified initialization

- README.md
[lsp-mode](https://github.com/emacs-lsp/lsp-mode) now supports yaml-language-server so added it to the client list.
> Add lsp-mode for Emacs client

- src/languageservice/jsonSchema04.ts
- src/languageservice/jsonSchema07.ts
- src/languageservice/parser/yamlParser07.ts
- src/languageservice/services/yamlCompletion.ts
- src/languageservice/services/yamlHover.ts
- src/languageservice/services/yamlSchemaService.ts
- src/languageservice/services/yamlValidation.ts
- test/fixtures/customMultipleSchemaSequences.json
- test/mulipleDocuments.test.ts
Fixes: https://github.com/redhat-developer/yaml-language-server/issues/196
The idea of this PR is described in: https://github.com/redhat-developer/yaml-language-server/pull/81#issuecomment-548788330
cc @andxu @itowlson
> Fix for schema sequences

- src/languageservice/services/yamlSchemaService.ts
- src/server.ts
Fixes: https://github.com/redhat-developer/yaml-language-server/issues/202
Problem was that the json schema service did not export FilePathAssociation so while that worked when using it as a type it didn't work when trying to construct it.
> Fix for FilePathAssociation when trying to use kubernetes schema

- src/server.ts
- test/integration.test.ts
The `kubernetes-json-schema` repository has moved to the `instrumenta` GH organization now:
<https://github.com/instrumenta/kubernetes-json-schema>
Also the original repository has not been updated from `1.14` with new versions `1.15` and `1.16`:
<https://github.com/garethr/kubernetes-json-schema/>
For this PR I have pointed at the same `1.14` version, tests still pass.
I have also tried bumping to `1.16` and the tests still pass, I can add that to this PR too if you'd like.
Resolves #207
> Updating kube schema location to new instrumenta org

- src/server.ts
The current schema version for kubernetes is still at 1.14.0 which is very outdated. @instrumenta repo's latest available version is 1.17.0
> Update kubernetes schema to latest available version 1.17.0

- src/languageservice/parser/yamlParser07.ts
- src/languageservice/services/yamlValidation.ts
- test/schemaValidation.test.ts
This fixes the case when there are multiple merge keys present and there is a duplicate key error thrown. 
Now, when multiple merge keys are present a duplicate key error should NOT be thrown.
> Fix issue with duplicate key error on merge keys

- src/languageservice/parser/jsonParser07.ts
- test/schemaValidation.test.ts
This new code is a port from the json schema 4 parser to the new json schema 7 parser. It basically replaces the merge key with the actual values of what the node value points to.
Fixes: https://github.com/redhat-developer/yaml-language-server/issues/180 and https://github.com/redhat-developer/vscode-yaml/issues/233
> Fixed merge key error with JSON schema

- src/languageservice/services/yamlCompletion.ts
We are loosing completion items which we can create from JSON Scheme(including items from `defaultSnippets` property ) in case if array is contains objects.
This PR is fixed that.
Signed-off-by: Yevhen Vydolob <yvydolob@redhat.com>
> Add call 'addSchemaValueCompletions'

- src/languageservice/services/yamlCompletion.ts
- src/languageservice/utils/json.ts
- test/defaultSnippets.test.ts
- test/fixtures/defaultSnippets.json
This PR makes default snippets behave more yaml-like (rather than json-like) and inserts the correct spaces depending on the context you are auto completing in.
> Made default snippets yaml-like and added tests

- src/languageservice/services/yamlSchemaService.ts
This PR allows the customSchemaProvider to receive multiple uri's, load them, and combine them into one giant schema. The giant schema is a oneOf schema. This technically means that multiple contributors can match a specific file and send a schema back to the language server but only the schema that's matching the current file contents will be used!
> Made yamlSchemaService accept multiple uris from requestCustomSchema

- src/languageservice/services/yamlCompletion.ts
- src/languageservice/utils/json.ts
- test/defaultSnippets.test.ts
- test/fixtures/defaultSnippets.json
This PR brings a few fixes for default snippets:
1. Array items are now correctly indented regardless of where you autocomplete from
2. Array items input the - automatically if needed
2. Default snippets can contain array of arrays
> Default snippet fixes for arrays

- src/languageservice/services/yamlSchemaService.ts
Changed oneOf to anyOf when multiple custom providers are matched to the same file so that you will on longer get the `Matches multiple schemas when only one must validate` error.
Fixes: https://github.com/redhat-developer/vscode-yaml/issues/273
> Changed oneOf to anyOf for multiple custom schema providers

- src/languageservice/services/yamlCompletion.ts
- test/defaultSnippets.test.ts
- test/fixtures/defaultSnippets.json
This fix changes the way defaultSnippets are handled on array items. Previously the code was not checking if the schema node was equivalent in some way to the current node you are trying to auto complete on. This lead to cases where defaultSnippets are being shown where they weren't supposed to.
Fixes: https://github.com/redhat-developer/yaml-language-server/issues/232
> Fix the way defaultSnippets behaves on array items

- src/languageservice/services/yamlCompletion.ts
- test/defaultSnippets.test.ts
- test/fixtures/defaultSnippets.json
In a default snippet if the body has a quoted boolean value we want to maintain the quotes for that boolean value:
```
{
"label": "foo",
"description": "Foo",
"body": {
"bar": "true"
}
}
```
So when inserted it becomes `bar: "true"`.
Likewise, if the boolean value is not quoted then we don't want to keep quotes.
So when inserted it would become `bar: true` 
See: https://github.com/redhat-developer/yaml-language-server/issues/225#issuecomment-582395470
> Maintain quotes for boolean values in defaultSnippets

- .travis.yml
.travis.yml files are now being validated on travis and I believe its why the current version of yaml language server won't release to npm on travis.
See: https://travis-ci.community/t/npm-deploy-failed-missing-api-key-but-i-have-set-it/6624/2
This PR seeks to fix this issue.
> Modify .travis.yml to work with new travis build configuration

- src/languageservice/utils/schemaUrls.ts
- test/integration.test.ts
- test/schema.test.ts
Kubernetes schema was upgraded to latest available 1.17.0 last month with #214. However, that was reverted, probably by error, in refactoring from commit 5530e9711a1e (in #157, merged a few days later).
This commit updates once more Kubernetes schema to 1.17.0.
NB: tests were updated because with schema 1.17.0, `oneOf/0/properties` does not have property `kind`.
> Update kubernetes schema to 1.17.0... again

- README.md
Added setting options like schemaStore in `README.md`.
Ref: [vscode-yaml settings](https://github.com/redhat-developer/vscode-yaml#language-server-settings)
> Added setting options like schemaStore in README.md

- README.md
`vim-lsp` now supports `yaml-language-server` so added it to the client list.
- Ref: [vim-lsp wiki](https://github.com/prabirshrestha/vim-lsp/wiki/Servers-YAML)
- Ref: [vim-lsp-settings supported-languages](https://github.com/mattn/vim-lsp-settings#supported-languages)
> Add vim-lsp for Vim client

- src/languageservice/parser/yamlParser07.ts
- test/documentSymbols.test.ts
- test/schemaValidation.test.ts
This PR parses Null literals correctly and stated by the YAML spec: https://yaml.org/type/null.html
> Issue 118 null literals

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.test.ts
Fix the missing space between ':' and value in YAML completion, especially for default values, but not only.
Fix issue https://github.com/redhat-developer/vscode-yaml/issues/281
> yaml completion: add a space between ':' and value

- src/languageservice/utils/paths.ts
- test/paths.test.ts
when trying to add a schema from a scoped package: `./node_modules/@amenity/schemas/myschema.json`, `isRelativePath` returns false and the server issues the following error: `Unable to load schema from '/./node_modules/...`
the fix: add `@` to regex pattern
> fix issue with `@` symbol in relative path

- package.json
- src/languageservice/services/yamlDefinition.ts
- src/languageservice/yamlLanguageService.ts
- src/server.ts
- test/findDefintion.test.ts
- yarn.lock
This would allow the user to jump from `$ref` to its definition. References https://github.com/microsoft/vscode-json-languageservice/pull/50 https://github.com/vscode-langservers/vscode-json-languageserver/commit/cea01c453e98b9ca5efcb27e098b39418913967d
> add support for textDocument/definition

- src/server.ts
Small patch to fix [#256](https://github.com/redhat-developer/yaml-language-server/issues/256).
When submitting partial settings objects to the language server using the `onDidChangeConfiguration` listener, the server was overwriting its default values with null values for every unspecified parameter.
> Fix Partial Configuration Bug

- .travis.yml
- package.json
- yarn.lock
This PR removes unneeded installServerIntoExtension and stops removing node modules from out/server because it's no longer needed
> Remove unneeded installServerIntoExtension

- README.md
- src/languageservice/utils/schemaUrls.ts
- test/autoCompletion2.test.ts
- test/autoCompletion3.test.ts
- test/fixtures/customMultipleSchemaSequences.json
- test/hover.test.ts
- test/schemaValidation.test.ts
https://github.com/SchemaStore/schemastore/commit/47574508df006fd2cf4fcb27ea755fc2a480517b moved to using SSL to serve resources from schemastore.org, with https://github.com/SchemaStore/schemastore/commit/10967162c0c1f0ab8aa07ae544067705f8328847 enforcing the `www` subdomain for the main site (with json schemas served from the `json` subdomain still).
> move to https endpoints for schemastore.org

- test/autoCompletion.test.ts
- test/schema.test.ts
When editing files for #264, missed a handful of them in the commit as I did not realize I had not saved the files in my editor like a dummy.
> fix remaining schemastore links to https

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.requiredproperties.test.ts
- test/fixtures/testRequiredProperties.json
it seems that a `\t` is used instead of 4 spaces. I thought that tabs shouldn't be used in yaml files. To investigate more. @JPinkney does it ring a bell to you?
```
1) yamlCompletion with required properties
doComplete
Insert required attributes at correct level:
AssertionError [ERR_ASSERTION]: 'top:\n\tprop1: $1' == 'top\n    prop1: $1'
+ expected - actual
-top:
-	prop1: $1
+top
+    prop1: $1
```
> Fix required attributes insertion with first array item

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion6.test.ts
- test/fixtures/testStringArray.json
For some reasons language server wants to insert `null` when create completion for string array.
This PR replace `null` with empty string `""`.
Related issue: https://github.com/redhat-developer/vscode-tekton/issues/340
> Insert empty string instead of 'null' for string array completion

- README.md
- src/languageservice/utils/paths.ts
- src/server.ts
- test/paths.test.ts
This PR serves a few purposes:
1. Handle multi-root workspaces better by looking for onDidChangeWorkspaceFolder events
2. Fix a bug where if you have a workspace like test with yaml file test underneath it:
```
test:
test.yaml
```
the yaml file wouldn't correctly associate with a schema.
3. If a language client doesn't send workspace folders in initialization it will allow the relative path resolver to pick workspaceFolders up after and use those for relative path resolution.
> Handle workspace folders better

- CHANGELOG.md
- README.md
- src/languageservice/parser/yamlParser07.ts
- src/languageservice/services/yamlSchemaService.ts
- test/autoCompletion.test.ts
- test/parser.test.ts
- test/schema.test.ts
Choose to use modeline with pattern `# yaml-language-server: $schema=<urlToTheSchema>`
Why?
- needs to make a choice :-)
- using directive likes using `#SCHEMA` for instance is creating an invalid file with current specifications state, so need to move to a comment-like `#`
- use `$schema` because it is what is used by VS Code for JSON schema
big advantages of allowing defining the schema in the file is that the filename can be whatever is needed. It avoids the requirement of specific file name pattern. It ensures users can use a schema in all IDEs, no need for a specific IDE integration (apart from relying on Yaml Language Server of course).
For instance in OpenShift dev console, there is no way for user to choose the filename. it would allow to add have completion/validation there.
> 204 support schema associations in file

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.test.ts
Fix: https://github.com/redhat-developer/vscode-yaml/issues/200
> Provide default object as completion snippet

- src/languageservice/parser/jsonParser07.ts
- test/jsonParser.test.ts
- test/yamlParser.test.ts
These changes are copied from https://github.com/microsoft/vscode-json-languageservice/blob/master/src/parser/jsonParser.ts, upon which this file appears to be based.
> Add validation of date and time formats

- src/languageservice/services/documentSymbols.ts
- test/documentSymbols.test.ts
Fix: https://github.com/redhat-developer/vscode-yaml/issues/285
> Fix document symbols computation if yaml has complex mappings

- .gitignore
- CHANGELOG.md
- README.md
- package.json
- src/languageservice/services/schemaRequestHandler.ts
- src/languageservice/services/yamlFormatter.ts
- tsconfig.esm.json
- tsconfig.umd.json
- yarn.lock
The build now _also_ produces libraries in ESM and UMD format. That makes it possible, for example, to use yaml-language-server in [Monaco Editor](https://microsoft.github.io/monaco-editor/) with the YAML language server running as a worker in the browser.
Summary of the Changes
==
**New Files**
* tsconfig.esm.json - configuration to compile the code as an ES module.
* tsconfig.umd.json - configuration to compile the code in UMD format.
The output for both is a new directory `/lib`.
**Modified Files**
* package.json - _added_ to the existing build the compiling of the code to ESM and UMD libraries/modules; bumped `@types/prettier` to the latest version.
*  .gitignore - added `lib/` so Git will ignore the untracked files in it.
* src/languageservice/services/schemaRequestHandler.ts - …
> Build as ESM and UMD libs

- CHANGELOG.md
- README.md
- package.json
- src/languageservice/services/schemaRequestHandler.ts
- test/shemaRequestHandler.test.ts
- yarn.lock
This PR fix scheme loading on Windows, in case if URI has window path, ie `c:\some\path\to\scheme.json`.
Fix: https://github.com/redhat-developer/vscode-yaml/issues/347
> Fix scheme load on windows with full path

- CHANGELOG.md
- src/languageservice/services/yamlCompletion.ts
- src/languageservice/utils/charCode.ts
- src/languageservice/utils/indentationGuesser.ts
- src/languageservice/utils/textBuffer.ts
- src/languageservice/yamlLanguageService.ts
- src/server.ts
- test/autoCompletion.test.ts
- test/defaultSnippets.test.ts
- test/textBuffer.test.ts
- test/utils/serviceSetup.ts
This PR replace hardcoded `\t` character in completion snippets.
It try to take space preference, if it not defined, it try to detect indentation by file content, if it is not possible it use double space for completion text indentation.
Fix: #283
> Use space for completion text instead of tab

- package.json
- src/languageservice/services/yamlSchemaService.ts
- test/yamlSchema.test.ts
- test/yamlScheme.test.ts
- yarn.lock
This PR based on #191, with resolving merge conflicts and tests.
> Add support of Yaml Schema

- .npmignore
With https://github.com/redhat-developer/yaml-language-server/pull/333 we use `yarn` to publish `next` version.
Before and now, we use [`npm`](https://github.com/redhat-developer/yaml-language-server/blob/master/.travis.yml#L16) to publish release version on LS. And there are [some difference](https://github.com/yarnpkg/yarn/issues/754) between `npm` and `yarn` on packaging, that difference cause that `out/server/*` was not included with `yarn` packaging, but it included by `npm`. 
This PR just fix that, and also remove some unnecessary files from npm package.
> Fix 'yarn pack', remove unnecessary files from npm package

- src/languageservice/jsonSchema.ts
- src/languageservice/parser/jsonParser07.ts
- src/languageservice/services/yamlSchemaService.ts
- src/languageservice/services/yamlValidation.ts
- src/languageservice/utils/parseUtils.ts
- test/schema.test.ts
- test/schemaValidation.test.ts
- test/utils/errorMessages.ts
- test/utils/verifyError.ts
Fix: #310
Also fix: https://github.com/redhat-developer/vscode-yaml/issues/373 partially, as I add `YAML`  for YAML syntax errors
Demo:
Schema with `title`:
Local schema:
Yaml error:
Problems:
Kubernetos schema:
> Add schema info to diagnostics

- src/languageservice/services/yamlCompletion.ts
- src/server.ts
- test/autoCompletion.test.ts
This is firs PR, fix completion snippet generation for object in array. We also have problem with settings synchronisation, in case if `editor.tabSize` set up in language scope `[yaml]` we not take in account it. This PR fix that, but it also requires fix in `vscode-yaml` which I'm going to provide.
For #329
> Fix completion indentation for object in array

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.test.ts
Fix issue when strings from example/default value pasted as numbers i.e. `'1'` was pasted like `1`, this PR change that, so now `"1"` will be pasted.
Fix: https://github.com/redhat-developer/vscode-yaml/issues/371
With schemas provided [there](https://github.com/redhat-developer/vscode-yaml/issues/371#issuecomment-701626267) and [there](https://github.com/redhat-developer/vscode-yaml/issues/371#issuecomment-702086392)
> Fix example string of type integer gets pasted as int

- src/languageservice/parser/isKubernetes.ts
- src/languageservice/services/yamlCompletion.ts
- src/languageservice/services/yamlHover.ts
This PR adds isKubernetes option to doHover. Basically what isKubernetes does is allows you to use a [special comparator](https://github.com/redhat-developer/yaml-language-server/blob/master/src/languageservice/parser/jsonParser07.ts#L585)  when evaluating oneOf/anyOf. This is needed because the [generic comparator](https://github.com/redhat-developer/yaml-language-server/blob/master/src/languageservice/parser/jsonParser07.ts#L1243) provided works well in the general case but breaks down when you have a ton of anyOf/oneOf like in the kubernetes schema: 
Part of https://bugzilla.redhat.com/show_bug.cgi?id=1888874
You'll need to set isKubernetes=true in yamlHover.ts before building then set:
```
"yaml.schemas": { …
```
> Add isKubernetes option to doHover

- src/languageservice/services/yamlCompletion.ts
- src/languageservice/services/yamlHover.ts
- src/languageservice/services/yamlValidation.ts
- src/languageservice/yamlLanguageService.ts
- src/server.ts
- test/integration.test.ts
- test/utils/testHelper.ts
This PR removes promise constructors since they aren't actually used anywhere. We've always just used Promise and never passed anything different in
npm run test
> Remove unneeded promise constructors

- src/languageservice/services/schemaRequestHandler.ts
- src/languageservice/services/yamlCompletion.ts
- src/languageservice/services/yamlHover.ts
- src/languageservice/services/yamlLinks.ts
- src/languageservice/services/yamlSchemaService.ts
- src/languageservice/yamlLanguageService.ts
- test/autoCompletion.test.ts
- test/customTags.test.ts
- test/defaultSnippets.test.ts
- test/findLinks.test.ts
- test/hover.test.ts
- test/integration.test.ts
- test/mulipleDocuments.test.ts
- test/schema.test.ts
- test/schemaValidation.test.ts
- test/utils/testHelper.ts
This PR renames all Thenables to Promises and removes a few pieces of code that are never called. There is 1 lingering Thenable that I didn't get rid of in server.ts. The type returned for formatterRegistration is a Thenable (all promises are thenable but not all thenables are promises) so we can't convert it.
https://github.com/redhat-developer/yaml-language-server/issues/138
Tested to see that the yamlValidation contribution, json schema store schemas, setting a schema manually, and the custom contributor api all still work and then ran npm run test
> Rename all applicable Thenables to Promise

- src/languageservice/parser/jsonParser07.ts
- test/schemaValidation.test.ts
Fix bug when only `else` section of `if/then/else` was applied during file validation
https://github.com/redhat-developer/vscode-yaml/issues/393
Take schema and yaml definition from issue description, now validation works correctly:
> Fix if/then/else shema conditions

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.test.ts
Fix error during completion when schema contains `null` value in enum, example:
```json
{
"kind": {
"enum": [
"project",
null
],
}
}
}
```
With this PR error is gone, but I have doubt about behaviour. 
We generate completion item with label `null` but insert only new line`\n`.
According to yaml spec
```yaml
kind:
```
and 
```yaml
kind: null
```
are equal, but maybe it would be better if we will insert `null\n` instead of just `\n`?
Found during https://github.com/redhat-developer/yaml-language-server/issues/344 investigation.
Use example schema and yaml content:
```yaml
kind: 
```
call completion after `kind: `, you should see completion list with two items `project` and `null`.
> Fix error on completion 'null' value

- src/languageservice/services/schemaRequestHandler.ts
- src/requestTypes.ts
- src/server.ts
- test/schemaRequestHandler.test.ts
This PR registers a non-standard LSP request used specifically for VSCode. This LSP request gets triggered when an HTTP/HTTPS request to a schema is being made. Instead of the server resolving the schema the language server will send the URI to the client-side to be resolved. This has to be done in order to circumvent signed certificate errors that happen when you are trying to fetch the schemas outside of VSCode. From my understanding, VSCode is using Electron which uses Chromium which has certs already installed so this is why we have to do it this way and can't just fetch the schemas normally. I assume this is also why vscode-json-languageservice does the same thing
https://github.com/redhat-developer/vscode-yaml/issues/107
The only …
> Register a non-standard LSP content request for resolving schemas on the client side

- src/languageservice/services/yamlCompletion.ts
- test/defaultSnippets.test.ts
When completion invoked on field which has value:
`name: <cursor>aName` and file has scheme which contains `defaultSnippets` for `name`: 
```json
"name": {
"type": "string",
"defaultSnippets": [
{
"label": "some",
"body": "some"
}
]
},
}
```
it contains one option `some`, but inserting of that item will break yaml, as it 'eats' space after `:`:
`name:someaName`, this PR fix that, and now it no break yaml, so editor should contain `name: someaName`.
Found during work on https://github.com/redhat-developer/vscode-tekton/issues/429
You may use schema example from this description, or try complete any yaml mapping value. Completion shouldn't breck  yaml syntax.
> Keep space before word after inserting completion

- README.md
Updates README.md. 
It resolves #228. 
No code changes- I was working on the Emacs client for the YAML language server in lsp-mode, and I noticed that it relies on this feature, which seems to be undocumented.
> update readme with example of an array of glob patterns for schema

- .github/workflows/CI.yaml
Currently, if you make a PR from a fork the CI will run and try (and fail) to login to quay. This fixes that issue by only making the docker parts happen when the PR is being merged
Should fix the CI tests for https://github.com/redhat-developer/yaml-language-server/pull/372 and https://github.com/redhat-developer/yaml-language-server/pull/373
> Don't login to docker registry on PRs

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.test.ts
Fixes empty completion list on empty file. I found that we add `holder: \n` text in to text document, if line on which completion called is empty(contains only white spaces and line delimiter). 
Such behaviour do not to allow to choose proper schema, as some(k8's) schemas has `additionalProperties: false`, 
but AST contains property `holder`.
This PR fix that, so if file is empty we add `{}`(empty object)
Fix: https://github.com/redhat-developer/vscode-yaml/issues/349
Configure vscode-yaml with 
```json
"yaml.schemas": {
"kubernetes": [
"kubernetes.yaml"
]
}
```
then open `kubernetes.yaml`, file should be empty, and call code completion, you should see :
> Fix empty completion list on empty file

- src/languageservice/services/yamlCompletion.ts
- test/defaultSnippets.test.ts
- test/fixtures/defaultSnippets.json
Add missing space after value from default snippets
Fix: #364
Just follow #364 description, with this PR you should see `name: some` instead of `name:some`
> Add space before value from default snippets

- src/server.ts
It seems that [vscode-languageserver](https://github.com/microsoft/vscode-languageserver-node/blob/master/server/src/common/workspaceFolders.ts#L39) automatically sends a `client/registerCapability` to the client if you use `onDidChangeWorkspaceFolders` on the server side. This means that currently the server will then send `client/registerCapability` even if the client doesn't support it. Since workspaceFolders don't have dynamicRegistration in the initialization according to the LSP spec, there's no way to tell if we should be using `onDidChangeWorkspaceFolders` and thus sending the `client/registerCapability` on the server side. This PR makes it so that `onDidChangeWorkspaceFolders` is only registered when the formatter dynamic …
> Check if dynamic registration is enabled before executing onDidChangeWorkspaceFolders

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.test.ts
Fixes wrong indentation in case if object has array with object and it belongs to upper array, see schema in https://github.com/redhat-developer/yaml-language-server/issues/376#issuecomment-745850083
#376
Use schema from https://github.com/redhat-developer/yaml-language-server/issues/376#issuecomment-745850083
and yaml file content: 
```yaml
components:
- id: ss
type: dd
se
```
call code completion after `se`, and insert `settings` completion item.
You should have same result as on:
> Fix indentation for object in array completion

- src/languageservice/parser/jsonParser07.ts
- test/hover.test.ts
Fix jsonParser when objects is null and doesn't continue with any symbol in yaml file.
no issue reference
problem:
Hover doesn't work when there is now symbol after property.
On this example no hover will be displayed on `objProperty`
```
obj:
objProperty:
```
`hover.test.ts: 'Hover on null property'`
> Hover doesn't work when there is now symbol after property

- src/languageservice/services/yamlFolding.ts
- src/languageservice/yamlLanguageService.ts
- src/languageservice/yamlTypes.ts
- src/server.ts
- test/yamlFolding.test.ts
Add implementation for [foldingRange](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_foldingRange) request. Most cases it should be exactly the same as vscode default folding for yaml.
Fix: #337
Open any yaml file and look on "folding" chevrons in editor line number panel:
Try to fold/unfold some regions, and look on folding range if they is what you expect.
> Implement folding range provider

- src/languageservice/services/yamlCompletion.ts
- src/languageservice/yamlLanguageService.ts
- src/server.ts
- test/autoCompletion.test.ts
- test/utils/testHelper.ts
enable defaultSnippet markdown description in schemas for code completion service
when schema has defaultSnippet and markdown description parameter set, jsonCompletion will ignores this markdown description because of undefined parameter `supportsMarkdown`
added unit-test
> fix: codeCompletion-with-defaultSnippet-and-makdown

- test/schemaValidation.test.ts
fix test
resource 'https://json.schemastore.org/composer' has probably changed?
previous test failed
no reference
changed unit test
when you open reference https://json.schemastore.org/composer there is title 'Package'. This is the new value for test.
> fix: test yaml-schema Package

- src/languageservice/services/yamlCompletion.ts
- test/defaultSnippets.test.ts
Completion with defaultSnippet doesn't work in this scenario:
```yaml
array:
#invoke here without "-"
```
fix Completion with defaultSnippet when node is array
https://github.com/p-spacek/yaml-language-server/issues/4
added unit test
> fix: completion with default snippet when node is array

- src/languageservice/services/yamlCompletion.ts
- test/defaultSnippets.test.ts
- test/fixtures/defaultSnippets.json
fix previous PR https://github.com/redhat-developer/yaml-language-server/pull/385 'enable defaultSnippet markdown description in schemas for code completion service'
the problem is there
```yaml
object:
propertyFromSnipper:  #completion here suggest 'propertyFromSnipper' again
``` 
fix previous PR
move `collectDefaultSnippets` into 'array' condition
added unite test
> fix codeCompletion with defaultSnippet and makdown

- src/languageserver/handlers/languageHandlers.ts
- src/yamlServerInit.ts
It seems that during refactoring https://github.com/redhat-developer/yaml-language-server/pull/381 we lost registration for folding range provider, this PR just return back that.
none
Folding ranges should works as before refactoring
> Return folding rage provider

- src/yamlServerInit.ts
- test/utils/testHelper.ts
Fixes services initialization, before we create two instances of `LanguageService` first with default client capabilities (for tests setup) and second when we receive real client capabilities, the problem in first as it was used to handle all requests from client. In that case we not handle client capabilities at all.
Found during work on https://github.com/redhat-developer/yaml-language-server/pull/395
Just run yaml-ls with this PR changes, you should not see any differences in LS behaviour
> Fix services initialization

- src/languageservice/utils/schemaUrls.ts
- test/integration.test.ts
Since Kubernetes schema has updated to 1.18.1, this commit is for updating schema version.
> Update kubernetes schema to 1.18.1

- README.md
- package.json
- src/commands.ts
- src/languageserver/commandExecutor.ts
- src/languageserver/handlers/languageHandlers.ts
- src/languageserver/handlers/notificationHandlers.ts
- src/languageserver/handlers/requestHandlers.ts
- src/languageserver/handlers/settingsHandlers.ts
- src/languageserver/handlers/validationHandlers.ts
- src/languageserver/handlers/workspaceHandlers.ts
- src/languageservice/parser/jsonParser07.ts
- src/languageservice/services/schemaRequestHandler.ts
- src/languageservice/services/yamlCodeActions.ts
- src/languageservice/services/yamlOnTypeFormatting.ts
- src/languageservice/services/yamlValidation.ts
- src/languageservice/utils/ranges.ts
- src/languageservice/yamlLanguageService.ts
- src/requestTypes.ts
- src/server.ts
- src/yamlServerInit.ts
- src/yamlSettings.ts
- test/defaultSnippets.test.ts
- test/findLinks.test.ts
- test/schemaRequestHandler.test.ts
- test/schemaValidation.test.ts
- test/utils/testHelper.ts
- test/utils/verifyError.ts
- test/yamlCodeActions.test.ts
- yarn.lock
Adds code action to open json schema, this code action will be available only for JSON Schema specific error/warnings, only for schemas which URI has `file`(local schemas) or `https` (remote, usually for schema store).
Demo:
> Note: to be able to open files from LS this PR also update `vscode-languageclient` to `7.0.0` version
VSCode extension part: https://github.com/redhat-developer/vscode-yaml/pull/418
https://github.com/redhat-developer/vscode-yaml/issues/174
To test this you need https://github.com/redhat-developer/vscode-yaml/pull/418 also, just build both and run extension, open any yaml file with schema associated, make some error in it, after error appeared  in editor, there are yellow bulb should appeared for line with error, just click on it, an click on `Jump to schema …
> Add code action to open json schema

- src/languageserver/handlers/requestHandlers.ts
- src/languageservice/services/yamlSchemaService.ts
- src/languageservice/yamlLanguageService.ts
- test/schema.test.ts
add schema modification to delete schemas from cache.
```ts
export enum MODIFICATION_ACTIONS {
'delete',
'add',
'deleteWhole',
}
```
when dynamically changing shared schema, I use this deleteWhole schema action to delete old parent schemas from cache. So language server will reload parents schemas with updated referenced schema. 
no ref
added unit test
> feat: add multiple schema deletions

- src/languageservice/parser/jsonParser07.ts
- src/languageservice/services/yamlCodeActions.ts
- src/languageservice/services/yamlValidation.ts
- src/languageservice/utils/parseUtils.ts
- src/languageservice/utils/textBuffer.ts
- src/languageservice/yamlLanguageService.ts
- test/customTags.test.ts
- test/schemaValidation.test.ts
- test/utils/verifyError.ts
- test/yamlCodeActions.test.ts
- test/yamlValidation.test.ts
This PR adds various things:
- Improves yaml parser diagnostics reporting, now diagnostics has proper text regions
- Collapse multiple `Using tabs can lead to unpredictable results` diagnostic in to one, previously we report each tab character separately
-  Add CodeAction to convert Tab characters to spaces
Demo:
https://user-images.githubusercontent.com/929743/109139137-d68d8a80-7763-11eb-995c-e1cd5e02462c.mov
Convert all tabs to spaces:
https://user-images.githubusercontent.com/929743/109173190-3f88f880-778c-11eb-8f69-acc9ca934657.mov
Fix: #244 
With new tests and manually, just create yaml file with tab's characters and see that  `Using tabs can lead to unpredictable results` error has CodeAction `Convert Tab to Spaces` and when it executed tabs replaced with spaces according to …
> Add CodeAction to convert Tab characters to spaces

- src/languageserver/handlers/settingsHandlers.ts
- test/settingsHandlers.test.ts
- test/yamlValidation.test.ts
It add `/` to file match pattern, if pattern doesn't include it.
The original problem in `vscode-json-languageservice`, it the way how file match implemented there.
Basically it match only file name end(i.e. `arc.yaml` and `.mocharc.yaml` file patterns will match to `/some/path/.mocharc.yaml`) 
This PR is basically, trying to workaround that behaviour, by forcing matching against full file name.
`vscode-json-languageservice` has similar issues:
- https://github.com/microsoft/vscode/issues/67191
- https://github.com/microsoft/vscode/issues/44135
Demo:
Fix: https://github.com/redhat-developer/vscode-yaml/issues/354
and fix: https://github.com/redhat-developer/vscode-yaml/issues/397
Just create `.mocharc.yaml` file, open it and make sure that JSON Schema selected properly.
> Fix 'fileMatch' pattern to match whole file name

- src/yamlServerInit.ts
Disable folding range provider, as with current parser we cannot implement it correctly, as it eats comments so we cannot calculate correct AST node end.
https://github.com/redhat-developer/yaml-language-server/issues/421 can help as thous parser correctly works with comments.
Fix: #400
> Disable folding range provider

- src/languageserver/handlers/settingsHandlers.ts
- test/settingsHandlers.test.ts
This PR re-adds in schema priority levels. Apparently, they got lost when I refactored everything
> Re-add schema priority levels

- src/languageserver/handlers/validationHandlers.ts
- src/languageservice/services/yamlValidation.ts
- test/schemaValidation.test.ts
Fixes validation for empty file or for file which contains only whitespace's (` `, `\n`, `\t`).
Fix: #413 
With tests.
To test manually open any yaml file with json schema associated, schema should contain required fields for root object, and yaml file should be empty or contains only whitespace characters, validation should work for such yaml file.
> Fix validation for empty file

- src/languageservice/utils/schemaUrls.ts
- test/integration.test.ts
According to https://github.com/instrumenta/kubernetes-json-schema/issues/26 we also need to change the referenced schema repository to https://github.com/yannh/kubernetes-json-schema/ that now contains latest/daily updated schemas.
> Update kubernetes schema to 1.20.5

- src/languageserver/handlers/languageHandlers.ts
- src/languageservice/jsonSchema.ts
- src/languageservice/parser/yaml-documents.ts
- src/languageservice/services/documentSymbols.ts
- src/languageservice/services/yamlCodeActions.ts
- src/languageservice/services/yamlCodeLens.ts
- src/languageservice/services/yamlCommands.ts
- src/languageservice/services/yamlCompletion.ts
- src/languageservice/services/yamlFolding.ts
- src/languageservice/services/yamlHover.ts
- src/languageservice/services/yamlLinks.ts
- src/languageservice/services/yamlValidation.ts
- src/languageservice/yamlLanguageService.ts
- src/yamlServerInit.ts
- test/utils/testHelper.ts
- test/yamlCodeActions.test.ts
- test/yamlCodeLens.test.ts
- test/yamlCommands.test.ts
Add CodeLens at the beginning of the file with all applied JSON Schema's, click on that CodeLans will open JSON Schema in separate tab:
https://user-images.githubusercontent.com/929743/111322351-81ada780-8671-11eb-94c7-1f98f0c0fe4c.mov
Als it improves opening schemas, now all possible type of schema is supported, including schema contributed from vscode-yaml api.
>Note: I still not able to add navigation to specific part of JSON Schema which cause an error, as we are losing information about positions during parsing JSON.
#412 
With tests and manual, just open any yaml file which has JSON Schema, CodeLens with name and file name should appears above first line.
> Show all json schemas for yaml file in codelens

- src/languageservice/services/yamlCompletion.ts
- src/languageservice/utils/textBuffer.ts
- test/autoCompletion.test.ts
Fix completion for existing property.
Demo:
https://user-images.githubusercontent.com/929743/111995901-26bcfa00-8b22-11eb-8c15-ee0c5f89ad41.mov
Fix: #414
With test.
>  Fix completion for existing property

- src/languageservice/services/yamlCompletion.ts
- src/languageservice/services/yamlSchemaService.ts
- test/autoCompletion.test.ts
It add support for `$ref` in `additionalItems`
Schema used from #408 description
Demo:
Fix: #408
With tests
> Add support $ref in additionalItems

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.test.ts
Use 'markdownDescription' for property completion.
Demo:
Fix: https://github.com/redhat-developer/vscode-yaml/issues/417
With test
> Use 'markdownDescription' for property completion

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.test.ts
Remove escape character `\"` from default values.
Demo:
https://user-images.githubusercontent.com/929743/113821333-a256b200-9784-11eb-8b1a-92e091a4b9d0.mov
#353 
With test and manually, use schema provided in #353 description, and try to complete `property1` value, it should be inserted without `\"` just `"`
> Remove escape character from default values

- .vscode/launch.json
- src/languageserver/handlers/settingsHandlers.ts
- src/languageservice/parser/yaml-documents.ts
- src/languageservice/utils/arrUtils.ts
- test/yaml-documents.test.ts
Fixes errors related to custom tags
>Also it add fix which removes warnings on test output window related to sourcemap if launch test with VSCode launch
https://github.com/redhat-developer/vscode-yaml/issues/461
With tests and manually, just follow https://github.com/redhat-developer/vscode-yaml/issues/461 add custom tags and open any yaml file which contains custom tags, there are no errors should present.
> Invalidate document cache if custom tags provided

- src/languageservice/utils/parseUtils.ts
- test/yamlParser.test.ts
- yarn.lock
It changes which schema we pass to yaml parser to fix support of recommended yaml tags. 
Fix https://github.com/redhat-developer/vscode-yaml/issues/173
With tests. To test manually just use any tag from [Recommended Schema](https://yaml.org/spec/1.2/spec.html#Schema)
> Fix YAML Schema usage

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.test.ts
Proper remove any number of `\` before `"` in completion inserted text 
Fix: #353 
with test
> Remove all '\' before '"' in completion text change

- package.json
- yarn.lock
Upgrade to the newer 4.1.0 version of vscode-json-languageservice
which enables used of the extended glob patterns.
Related: https://github.com/microsoft/vscode-json-languageservice/pull/93
> Upgrade vscode-json-languageservice

- .vscode/launch.json
- src/languageservice/parser/ast-converter.ts
- src/languageservice/parser/yaml-documents.ts
- src/languageservice/parser/yamlParser07.ts
- src/languageservice/utils/parseUtils.ts
- test/documentSymbols.test.ts
- test/schema.test.ts
- yarn.lock
Fix build.
Fix new parser AST range convert to offset + length.
This is fix all Document Symbols tests.
>Note: This PR changed convert of `Alias` node, nowit converted to `StringASTNodeImpl` instead of resolving to declaration node. As JSON AST don't support such nodes, Document Symbols calculation is breaking LSP rules on `SelectionRange`
> Fix range convert to offset+length

- src/languageserver/handlers/validationHandlers.ts
- src/languageservice/parser/jsonParser07.ts
- test/schemaValidation.test.ts
Primarily, this adds support for recursively expanding multiple levels of aliases. In the process I made some other minor changes:
* `validateTextDocument` was swallowing errors which made my test pass when it should have failed. I think propagating errors could result in "unhandled promise rejection" errors in logs but I think that's better than ignoring them?
* Double-negative typos in a few tests I saw
* I added a test for a very particular case of anchor error rendering. I initially thought this was broken, but it appears intentional so I wanted to encode it in a test since it seems easy to regress.
#273
Wrote a test. Ran this in development against a YAML file/schema that was giving me trouble.
> Handle nested anchors in validation expansion (Fixes #273)

- README.md
Add [monaco-yaml](https://github.com/pengx17/monaco-yaml) in the readme under clients.
N/A
No
> Add monaco-yaml in the readme under clients

- src/languageserver/handlers/settingsHandlers.ts
- src/languageservice/parser/jsonParser07.ts
- src/languageservice/services/yamlValidation.ts
- src/languageservice/yamlLanguageService.ts
- src/yamlSettings.ts
- test/schemaValidation.test.ts
Add `disableAdditionalProperties` into yaml configuration and if is set to true yaml validation won’t allow extra props that are not in schema (where type == 'object').
By default we can achieve same behave with setting each of schema object by property `additionalProperties = false`.
But this global `disableAdditionalParameters` set this globally for all object schemas.
For my purpose I'm using this to quickly switch between strict validation mode and not-strict.
no ref
added tests
> Feat: Add config parameter to disable additional properties

- src/languageservice/parser/recursivelyBuildAst.ts
- test/yamlParser.test.ts
Fix "Billion Laughs" attack, by limiting of recursion depth in `recursivelyBuildAst` function.
Demo:
https://user-images.githubusercontent.com/929743/118645793-0e96ed80-b7e8-11eb-86be-b26801a72c81.mov
#463 
with test and manually.
> Fix "Billion Laughs" attack

- README.md
- src/languageserver/handlers/settingsHandlers.ts
- src/yamlSettings.ts
Adds option to specify custom schema store schema
https://github.com/redhat-developer/vscode-yaml/issues/294
https://github.com/redhat-developer/vscode-yaml/issues/406
This change is published here: https://www.npmjs.com/package/@hackercat/yaml-language-server (with few changes in tests and my own schema store mirror) since I've tested it few times with custom store and clearing cache.
I think that the change is fairly small and easy to review. I'd appreciate any pointers since I never had any experience (except JS) with NodeJS/TS/NPM/etc. before and this whole thing was hacked in few hours (90% of time trying to figure out how to build this whole thing with `vscode-yaml` extension, it was a lot of `yarn this`, `yarn that`, I've not run `yarn test` for `vscode-yaml` extension since …
> feat: add option to specify custom schema store

- src/languageserver/handlers/settingsHandlers.ts
- test/settingsHandlers.test.ts
Remove fileMatch workaround as now we have proper glob patterns support.
https://github.com/redhat-developer/vscode-yaml/issues/508
with test
> Remove fileMatch workaround

- src/languageservice/parser/ast-converter.ts
- src/languageservice/parser/jsonParser07.ts
- src/languageservice/parser/yaml-documents.ts
- src/languageservice/services/yamlValidation.ts
- test/schemaValidation.test.ts
- test/utils/errorMessages.ts
- test/yamlValidation.test.ts
PR fix  "Billion Laughs" attack for new AST transformer.
Also changes AST transformer for `ref` mapping key and restore resolving `ref` nodes.
Also fix test in `schemaValidation.test.ts` (except one test related to duplicate keys) and `yamlValidation.test.ts`
> Fix "Billion Laughs" attack and validation tests

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.test.ts
This PR makes it so that colons inside of a yaml key are automatically quoted
Fixes https://github.com/redhat-developer/vscode-yaml/issues/496 and https://github.com/redhat-developer/yaml-language-server/issues/474
Tested manually through vscode and through the test I've created
> Make autocomplete automatically escape colon inside of a key

- src/languageserver/handlers/settingsHandlers.ts
- src/yamlServerInit.ts
- src/yamlSettings.ts
- test/settingsHandlers.test.ts
- test/utils/testsTypes.ts
It changes the way how LS receives settings/preferences, previously we fully rely on client, which use deprecated API to push settings to server. Now we use proper API to fetch settings from client.
Resolve #327
with test, and manually, just run vscode-yaml and make sure that your preferences used on yaml-ls.
> Use 'workspace/configuration' to fetch settings

- src/languageservice/parser/yaml-documents.ts
It fixes error:
```
Error - 2:38:37 pm] (node:5928) UnhandledPromiseRejectionWarning: TypeError: customTags.filter is not a function 
at Object.filterInvalidCustomTags (c:\Users\_username_\.vscode\extensions\redhat.vscode-yaml-0.20.0\node_modules\yaml-language-server\out\server\src\languageservice\utils\arrUtils.js:56:23)
at Object.customTagsToAdditionalOptions (c:\Users\_username_\.vscode\extensions\redhat.vscode-yaml-0.20.0\node_modules\yaml-language-server\out\server\src\languageservice\utils\parseUtils.js:51:37) 
at Object.parse (c:\Users\_username_\.vscode\extensions\redhat.vscode-yaml-0.20.0\node_modules\yaml-language-server\out\server\src\languageservice\parser\yamlParser07.js:79:44) 
at YamlDocuments.ensureCache (c:\Users\_username_\.vscode\extensions\redhat.vscode-yaml-0.20.0\node …
```
> initialise 'customTags' parameter with default value

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.test.ts
Fix error when completion item label not string
Fix: https://github.com/redhat-developer/vscode-yaml/issues/536
with test
> Fix error when completion item label not string

- README.md
- src/languageservice/services/yamlSchemaService.ts
- test/autoCompletion.test.ts
Add support for relative and absolute path in inline schema comment:
```yaml
```
Resolve: #371
With tests
> Support relative path in inline schema comment

- src/server.ts
Include call stack when `console.error` called with null.
As in yaml-ls we bind `console` to `connection.console` all calls of `console.error` and `console.log` goes to `connection` and if they contains `Error` we send such messages to telemetry. But `console.error` may be used in yaml-ls dependencies,
so this PR add ability to find which exactly code call `console.error` with `null` argument.
Part of https://github.com/redhat-developer/vscode-yaml/pull/552
> Include call stack when console error called with null

- src/languageservice/services/documentSymbols.ts
- src/languageservice/services/yamlCodeLens.ts
- src/languageservice/yamlLanguageService.ts
- test/yamlCodeLens.test.ts
To resolve https://github.com/redhat-developer/yaml-language-server/issues/496 and https://github.com/redhat-developer/yaml-language-server/issues/497 we need more info on thous errors, this PR add direct telemetry logging.
As par for #496 and #497
> Send errors to telemetry

- src/languageserver/handlers/settingsHandlers.ts
- test/settingsHandlers.test.ts
This PR tweaks the way the `http` configuration section is pulled from the client. It pulls the entire `http` section at once then plucks out the values it needs. I do assume there is no sensitive client information other that `proxy` and `proxyStrictSSL` on the `http` section which shouldn't be pulled.
In my research I've found no solid definition for what a `section` in the LSP is so my thinking is that usage of it should be as simple as possible for most clients to support it.
[Nova](https://nova.app) doesn't currently have a way to configure how workspace settings are passed to the server and it does it in a bit of an odd way at the moment, which I've described in the issue below. Requesting `http.proxy` in Nova returns `{}` which was getting passed straight to `requests_light` and …
> Fix fetching nested http settings

- src/languageservice/services/yamlCompletion.ts
- src/languageservice/services/yamlHover.ts
- src/languageservice/services/yamlSchemaService.ts
- test/autoCompletion.test.ts
- test/hover.test.ts
In some features (like codecompletion and hover) we miss checks, that ensures that JSON Schema was parsed,
this PR add them. It should fix errors like https://github.com/redhat-developer/vscode-yaml/issues/556 and https://github.com/redhat-developer/yaml-language-server/issues/497
https://github.com/redhat-developer/vscode-yaml/issues/556
https://github.com/redhat-developer/yaml-language-server/issues/497
With test and manually, try  https://github.com/redhat-developer/vscode-yaml/issues/556
> Fix bad schema handle

- src/server.ts
Redirect `null` error to `console.log` instead of `console.error`.
To not track that `null` message in telemetry.
> That `null` message appears from `vscode-nls` library, which in some cases cannot load configuration file.
> Do not send 'null' in to telemetry

- src/languageservice/services/yamlSchemaService.ts
- test/yamlSchemaService.test.ts
It add support of referencing to `#/definitions/{SomeObjectInSchema}`  in JSON Schema URL.
Before `0.21.0` we have support of such URL, but that support was because of bug in schema priority code.
In  `0.21.0` that bug was fixed and we loose of support. This PR add proper implementation of referencing in schema URL.
Resolve: https://github.com/redhat-developer/vscode-yaml/issues/557
With test. 
To test manually reproduce steps from https://github.com/redhat-developer/vscode-yaml/issues/557
> Add support of URL fragments in schema URL

- src/languageserver/handlers/settingsHandlers.ts
- test/settingsHandlers.test.ts
Fix unhandled promise rejection, when client doesn’t support dynamic registration.
Fix: #498
with tests
> Fix unhandled promise rejection in configuration handler

- package.json
The intention was to enforce developers of the project to use a minimal version of yarn. However, the yarn and npm engines determine which version of those package managers may be used to install `yaml-language-server`. This caused warnings for users using npm or older yarn versions.
The node engines field signals required node version that’s needed. Setting it to `*` is equivalent to not setting it at all.
Closes #521
The CI logs in https://github.com/remcohaszing/monaco-yaml/pull/88/checks?check_run_id=3390781647 show the annoying warning. This is the closest reference to a test case I could think of.
> Remove engines from package.json

- README.md
This updates the link to the `monaco-yaml` project in the readme.
The project was transferred to my account. I created a demo on the updated link.
N/A
I clicked the link. :)
> Update monaco-yaml link

- package.json
- yarn.lock
The updated dependencies match the ones from `vscode-json-languageservice`. This means they can be deduped. This is mostly interesting to decrease bundle size for usage in the browser, such as in `monaco-yaml`.
N/A
```sh
yarn test
```
> Update vscode-nls and vscode-uri

- package.json
- src/languageservice/services/yamlSchemaService.ts
- yarn.lock
In #442 `yaml-language-server-parser` is being replaced with `yaml` for parsing the AST. `yaml` can also replace `js-yaml` for parsing YAML in other places. This saves a dependency.
N/A
Existing unittests didn’t break.
> Replace js-yaml with yaml

- src/languageservice/parser/recursivelyBuildAst.ts
- src/languageservice/services/yamlCodeLens.ts
- src/languageservice/services/yamlHover.ts
- src/languageservice/yamlLanguageService.ts
It fix possible issue in `recursivelyBuildAst` which can cause https://github.com/redhat-developer/vscode-yaml/issues/583 and https://github.com/redhat-developer/vscode-yaml/issues/584
Also this PR enhance error handling in `hover` and `codelens` implementations.
Fix https://github.com/redhat-developer/vscode-yaml/issues/583 
Fix https://github.com/redhat-developer/vscode-yaml/issues/584
No, as currently telemetry doesn't have enough information about errors.
> Fix error handling in hover and codelens

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.test.ts
- escape keys in `part-a(\s+)?:(\s+)part-b` format (as introduced in #475)
- do not escape keys in `part-a:part-b` or `:partb` format
#571 
Tested locally by running `yarn run test`
> Stop escaping valid string keys

- src/languageservice/parser/json-schema07-validator.ts
- src/languageservice/parser/jsonParser07.ts
- src/languageservice/utils/strings.ts
- test/strings.test.ts
Fix `RegExp` object creating with `'u'` flag in case of old patterns, which not written with unicode support.
https://github.com/redhat-developer/vscode-yaml/issues/633
With test
> Unescape regexp string to be compatible with 'u' flag

- src/languageservice/utils/strings.ts
- test/strings.test.ts
Provide fallback to regular regexp if we cannot create unicode. As JSON schema spec, before `2020-12` version, doesn’t describe that regexp should support unicode, most of existing patterns will not work with `u` flag.
Fix: https://github.com/redhat-developer/vscode-yaml/issues/636
With test
> Fallback to regular regexp if we cannot create unicode

- src/languageserver/handlers/languageHandlers.ts
- src/languageservice/services/yamlDefinition.ts
- src/languageservice/yamlLanguageService.ts
- src/yamlServerInit.ts
- test/findLinks.test.ts
- test/yamlDefinition.test.ts
Add implementation for definition request, which allows to navigate from alias to anchor node:
https://user-images.githubusercontent.com/929743/140951209-cf7de5a8-cfce-40a9-b720-38a0b716f4b0.mov
Resolve https://github.com/redhat-developer/yaml-language-server/issues/541
With test
> Add implementation for definition request

- package.json
- yarn.lock
Copy of https://github.com/redhat-developer/vscode-yaml/pull/644 , fixing a redirect follow bug in request-light v < 0.5.5
THe non existend copy of https://github.com/redhat-developer/vscode-yaml/issues/586 in this repo :D
I'm using this with the neovim lsp installation. Before this patch a `.graphqlrc.yaml` file would error since the schema https://unpkg.com/graphql-config/config-schema.json does a relative redirect to https://unpkg.com/graphql-config@4.1.0/config-schema.json` (note the version). With this version it works.
> bump request light version

- src/languageservice/parser/yaml-documents.ts
- test/yamlSchemaService.test.ts
Fix collecting comments, in case when document contains several commented line in a row, like:
```yaml
#first comment
#second comment
foo: bar
```
Fix: https://github.com/redhat-developer/vscode-yaml/issues/629
With test
> Fix collecting comments from AST

- src/languageservice/services/documentSymbols.ts
- test/documentSymbols.test.ts
Fix `yaml.hierarchicalDocumentSymbols.error` error message on telemetry.
That can be caused when mapping key is not string.
none
with tests.
> Fix document symbols, when key is not string

- src/languageservice/services/yamlCodeLens.ts
- src/languageservice/services/yamlDefinition.ts
- src/languageservice/services/yamlHover.ts
- src/languageservice/services/yamlLinks.ts
- src/languageservice/yamlLanguageService.ts
It fixes telemetry error reporting for `links` feature. 
Also it change sending errors to telemetry, as `JSON.stringify()` return empty string for `Error`
None, we have a lot of `Request textDocument/documentLink failed. Message: Request textDocument/documentLink failed with message: Cannot read property 'sendError' of undefined`
manually
> Fix links error reporting

- src/languageservice/services/yamlSchemaService.ts
- test/yamlSchemaService.test.ts
Fixes fragments when schema URL is a local file.
Example of such a reference:
```
```
Currently this doesn't work in VS Code:
Error on hover is:
```
Unable to load schema from '/path/to/schemas/example.schema.json#/definitions/CustomSpec': No content.YAML(768)
```
The issue is caused by "#" being turned into "%23" during some path resolve operations. This PR fixes it by excluding the fragment during those operations.
Couldn't find a GitHub issue.
Relates somewhat to old PR which added fragment support: #530
Includes automated test in existing suite.
I don't know how to test this with VS Code directly (if you could advice, I'll happily test locally; as a sidenote, CONTRIBUTING.md in this regard would be helpful).
> Fix relative file paths with fragments

- src/languageservice/utils/schemaUrls.ts
- test/autoCompletionFix.test.ts
- test/integration.test.ts
Update K8S json schema version
The latest version is 2 minor version ahead of current, update it to prevent outdated validation.
> Update K8S json schema version from 1.20.5 to 1.22.4

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.test.ts
extends array documentation on completion
before:
after:
no ref
modified UT
> feat: extend array documentation on completion

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.test.ts
add more detail into anyOf array completion
instead of simple array index
It's display real related type name
```yaml
"test_array_anyOf_2objects": {
"items": {
"anyOf": [
{ "$ref": "#/definitions/obj1" },
{ "$ref": "#/definitions/obj2" },
{ "$ref": "#/definitions/obj3" }
]
},
"type": "array"
},
```
fixed tests that seem not running/failing
no ref
modified UT
> feat: add more detail into anyOf array completion

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.test.ts
- test/autoCompletionFix.test.ts
- test/defaultSnippets.test.ts
Simplify simple (with one variable) code completion when the text ends with $1.
For the user, it's quite complicated to not forget to hit `tab` instead of `enter`.
Note: not sure if it makes sense for your users. I would like to know your opinion. For me/users it's not very handy to use tab and enter together in these simple completion scenarios.
Before:
https://user-images.githubusercontent.com/38421337/144215088-c30c8663-3ee9-4c24-8ea2-d1fa7fa857f1.mov
After: 
https://user-images.githubusercontent.com/38421337/144215152-46e0f44d-3aea-47e8-9336-bb752b91f00b.mov
no ref
modified UTs
> feat: trim end $1 from completion

- package.json
- src/languageservice/parser/ast-converter.ts
- src/languageservice/parser/jsonParser07.ts
- test/jsonParser.test.ts
- test/yamlParser.test.ts
Fix: 'Cannot read property 'type' of undefined' error and remove direct dependency on 'jsonc-parser' module.
Fix: https://github.com/redhat-developer/vscode-yaml/issues/652
with test
> Fix: 'Cannot read property 'type' of undefined'

- src/languageserver/handlers/settingsHandlers.ts
- src/languageservice/services/documentSymbols.ts
- src/languageservice/services/yamlCodeLens.ts
- src/languageservice/services/yamlCompletion.ts
- src/languageservice/services/yamlDefinition.ts
- src/languageservice/services/yamlHover.ts
- src/languageservice/services/yamlLinks.ts
- src/languageservice/services/yamlValidation.ts
- src/languageservice/utils/objects.ts
- src/server.ts
- test/objects.test.ts
It ensures that we send errors to telemetry with stack traces. 
Also it add `uncaughtException` error handler for  yaml-ls `process` to track errors and sand them with stack trace to telemetry. That should add possibility to detect `Maximum call stack size exceeded` errors.
None, but it help with issues like https://github.com/redhat-developer/vscode-yaml/issues/652 where we have only error message, but we don't have any trace.
manually
> Improve telemetry errors

- src/languageservice/parser/yaml-documents.ts
- test/autoCompletionFix.test.ts
fix: completion invoke in three different scenarios
1) with short nextLine - nested object
2) with a new line inside the object
3) on the first array item
-----
1) when the cursor is closer to the next element than the previous one
```yaml
example:
sample:
a: test # 'a' is closer to the curseor then 'sample'
```
2) when the cursor is on the first line just inside the object
```yaml
example:
sample:
prop: test
```
3) when the cursor is on the first item array position
```yaml
examples:
- sample:
prop: test
```
no ref
added unit tests
> fix: completion invoke in three different scenarios

- src/languageservice/services/yamlCodeActions.ts
- test/code-action-schema.test.ts
Adds a codeaction that converts string `true` or `false` to boolean when boolean is expected.
related to #532 
Unit tests added
> Add convert to boolean code action

- src/languageservice/parser/yaml-documents.ts
Removes the getSchemas function from `SingleYAMLDocument` in favor of `getMatchingSchemas`.
Used the current test set.
> Remove getSchemas

- package.json
- yarn.lock
This is a around #585 by locking `vscode-json-languageservice` to version 4.1.8.
It’s a workaround, not a desirable fix.
#585\
microsoft/vscode-json-languageservice#123
All steps are run from the project root using `vim` and the following configuration:
```viml
au User lsp_setup call lsp#register_server({
\ 'name': 'yaml',
\ 'cmd': {server_info->['node', 'out/server/src/server.js', '--stdio']},
\ 'allowlist': ['yaml'],
\})
call plug#begin('~/.vim/plugged')
Plug 'prabirshrestha/vim-lsp'
call plug#end()
```
Clone and setup the project
```sh
git clone git@github.com:redhat-developer/yaml-language-server.git
yarn
yarn compile
yarn add vscode-json-languageservice@4.1.8
```
Create a file named `app-definition.yaml` with the following content. Use vim to edit it.
```yaml
name: 123
```
This …
> Lock vscode-json-languageservice@4.1.8

- README.md
- src/languageserver/handlers/settingsHandlers.ts
- src/languageservice/services/yamlCompletion.ts
- src/languageservice/yamlLanguageService.ts
- src/yamlSettings.ts
- test/autoCompletion.test.ts
Add config to exclude not required default props from completion.
fix: required prop with default value or with const
The reason why users appreciated this feature is that users don't have to specify default properties. Only if the default value needs to be changed, it makes sense to add them (but not all of them automatically).
no ref
add unit tests
> feat: disable default props

- src/languageservice/parser/jsonParser07.ts
- test/jsonParser.test.ts
This PR updated the maxMatch value based on the oneOf size. Because there may be a chances that node value matches all the schema which provided under oneOf 
https://github.com/redhat-developer/yaml-language-server/issues/586
Yes with test cases.
> updated maxMatch value based on oneOf size

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletionFix.test.ts
Array indent doesn't work properly inside another array.
https://user-images.githubusercontent.com/38421337/147991614-4871277e-3b79-4d7a-9a67-2158cba9afa6.mov
schema:
```json
{
"definitions": {
"arrayIndent": {
"examples": {
"type": "array",
"items": {
"objectWithArray": {
"type": "array",
"items": {
"required": ["item", "item2"],
"item": { "type": "string" },
"item2": { "type": "string" }
}
}
}
}
}
}
}
}
},
"type": "object"
}
```
yaml
```yaml
arrayIndent:
examples:
- 
```
```yaml
arrayIndent:
examples:
- objectWithArray:
- item: 
item2: # there should be the same indent
```
no ref
UT
> fix: Array indent doesn't work properly inside another array

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletionFix.test.ts
https://user-images.githubusercontent.com/38421337/148134131-4fc930d4-4c39-41f8-99a9-599fd104cfd4.mov
note: in the video `examples: \n -` is extra and doesn't have an effect to the bug behavior.
```yaml
objectWithArray:
- item: first item
item2:
prop1: extra indent
prop2: 
```
no ref
UTs for the 1st and 2nd item
> fix: array indent on different index position

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.test.ts
Add the possibility to suggest and insert the whole object structure. So a user doesn't have to add required properties one by one.
Another advantage is when a user has to pick between a few 'anyOf' objects.
It also works with incomplete objects.
Display two possibilities (anyOf) of complex objects and insert the whole structure of all required props of the object. 
https://user-images.githubusercontent.com/38421337/147861510-b2aa75ea-b583-4fa8-8b07-8f213cddd7b2.mov
Suggest the rest of the 'parent' object (missing required props).
https://user-images.githubusercontent.com/38421337/147861490-bd2032eb-64e5-48c9-9a6f-02abeda0723f.mov
Added also feature that adds const value instead of $1. So instead of `prop: {$1:value}` is used prop: value. (beginning of the second video)
no ref
few unit …
> feat: parent completion

- package.json
- src/languageserver/handlers/validationHandlers.ts
- src/languageservice/jsonASTTypes.ts
- src/languageservice/parser/ast-converter.ts
- src/languageservice/parser/jsonParser07.ts
- src/languageservice/parser/yaml-documents.ts
- src/languageservice/parser/yamlParser07.ts
- src/languageservice/services/validation/types.ts
- src/languageservice/services/validation/unused-anchors.ts
- src/languageservice/services/yamlCodeActions.ts
- src/languageservice/services/yamlCompletion.ts
- src/languageservice/services/yamlValidation.ts
- src/languageservice/utils/astUtils.ts
- src/languageservice/utils/strings.ts
- test/utils/verifyError.ts
- test/yamlCodeActions.test.ts
- test/yamlValidation.test.ts
- yarn.lock
It add diagnostic report for unused anchors, also it add code action which delete unused anchor.
This PR also updates the `yaml` parser to `2.0.0-9` to be able to use `CST` `scrToken` from  `Node`.
Demo:
https://user-images.githubusercontent.com/929743/146509097-9444b434-53d1-4d11-9a7c-f4c426f51726.mov
Resolve: https://github.com/redhat-developer/yaml-language-server/issues/587
with test
> Add diagnostic and code action for unused anchor

- src/languageservice/parser/yaml-documents.ts
- src/languageservice/services/yamlCompletion.ts
- test/schemaValidation.test.ts
It uses copy of AST for completion, as during completion we modify AST and that modification can trigger validation errors.
Fix: https://github.com/redhat-developer/vscode-yaml/issues/671
with test
> Use copy of AST for completion

- src/languageservice/parser/jsonParser07.ts
This PR checks the multiple  schema matches under oneOf based on the sub schema properties matches value
https://github.com/redhat-developer/vscode-yaml/issues/683
https://github.com/redhat-developer/yaml-language-server/issues/586
yes with test cases
> fix mulitple schema matches in oneOf based on the propertiesMatches value

- src/languageservice/parser/jsonParser07.ts
- src/languageservice/services/yamlSchemaService.ts
- test/schemaValidation.test.ts
Add check if schema is `object` in validation function.
Fix: https://github.com/redhat-developer/yaml-language-server/issues/652
with test
> Handle case when schema not JS object

- src/languageservice/services/validation/unused-anchors.ts
- src/languageservice/services/yamlCodeActions.ts
- test/utils/verifyError.ts
- test/yamlCodeActions.test.ts
- test/yamlValidation.test.ts
The anchor name was added as custom data. It’s unnecessary, because the name of the anchor can be determined from other values in the place where it’s used.
Because Monaco Editor marker data doesn’t support custom data, this blocks supports code actions in monaco-yaml.
Manually using monaco-yaml and using tests.
> Remove data from unused anchor diagnostics

- src/languageservice/services/yamlCodeLens.ts
- test/yamlCodeLens.test.ts
Merges schema URLs to avoid duplicate code lenses created. 
fixes #666
Adds a test that checks that there is only one code lens when there are multiple YAML documents.
> Remove duplicate codelens entries

- src/languageservice/services/yamlHover.ts
- test/hover.test.ts
If "examples" is defined in the schema, display it on the hover.
I think it useful to show what kind of input is expected for a string in user format.
A test was added.
> Add: show examples on hover.

- src/languageservice/parser/jsonParser07.ts
- test/schemaValidation.test.ts
The PR will check the oneOf array and do the type check against the schemas mentioned over it if the particular schema object has, instead of directly check the schema object type.
https://github.com/redhat-developer/vscode-yaml/issues/692
Yes with UT
> Schema validation should check the object's oneOf if it has instead of the object type

- src/languageservice/services/yamlFolding.ts
- src/yamlServerInit.ts
- test/yamlFolding.test.ts
Enables folding ranges. Adds the ability to fold documents when there is more than one document. Adds tests for making sure comments are not part of a region.
fixes https://github.com/redhat-developer/vscode-yaml/issues/413
fixes https://github.com/redhat-developer/vscode-yaml/issues/561
2 new tests are added to cover the case.
> Re-enable folding ranges

- package.json
- src/languageservice/jsonSchema.ts
- src/languageservice/services/yamlCompletion.ts
- src/languageservice/utils/json.ts
- test/autoCompletion.test.ts
- test/defaultSnippets.test.ts
- test/fixtures/defaultSnippets.json
fix various snippets problems:
- array of strings that was split into chars
- remove extra line between objects inside array
- indent from nested object inside array
- remove extra spaces after property colon
add property `sortText` into defaultSnippets, so it's possible to sort snippets inside code-completion panel
no ref
added unit tests and fixed existing
> fix: defaultSnippets insert text

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.test.ts
Auto completion should not suggest const value from schema for Array
https://github.com/redhat-developer/yaml-language-server/issues/620
Yes. with UT
> fixed auto completion not suggest const for array

- test/yamlSchemaService.test.ts
The fixed drive letter causes the test to fail if no such drive exists on the host OS.
> Make test agnostic of drive letter

- src/languageserver/handlers/schemaSelectionHandlers.ts
- src/languageserver/handlers/settingsHandlers.ts
- src/languageservice/jsonSchema.ts
- src/languageservice/services/yamlSchemaService.ts
- src/languageservice/yamlLanguageService.ts
- src/languageservice/yamlTypes.ts
- src/requestTypes.ts
- test/schemaSelectionHandlers.test.ts
- test/settingsHandlers.test.ts
Add support for versions in JSON Schema store.
Demo:
https://user-images.githubusercontent.com/929743/157059235-97c3cb6c-ef5a-4cd5-97d6-3ac48e6d22e6.mov
Resolve #639
> Support JSON Schema versions from schemastore

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.test.ts
If multiple schemas inside of `anyOf` have the same final calculated schema name, 'parent/skeleton' autocompletion merge properties from different schema into one completion item.
wrong merge of multiple subschemas:
after fix:
note that a fixed example is not ideal. Schema creator should add titles into the schemas for a proper fix.
```json
"leftElement": {
"anyOf": [
{
"properties": { ... },
"title": "Option 1"
},
{
"properties": { ... },
"title": "Option 2"
},
...
]  
```
modified Unit test
- the previous unit test doesn't make much sense
> fix: differentiate similar schemas on completion

- test/hover.test.ts
The upstream schema has changed and moved its definitions. This removes the references to upstream and makes the tests self-contained.
> Fix test failure due to reference to upstream schema

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.test.ts
- test/autoCompletionFix.test.ts
try to merge simple property completion from anyOf objects.
It's used syntax for choice in snippets: `${1|one,two,three|}` https://code.visualstudio.com/docs/editor/userdefinedsnippets#_choice
original:
https://user-images.githubusercontent.com/38421337/159483927-2ed0e8db-4407-4d5d-82aa-cf6daae38148.mov
after this PR:
https://user-images.githubusercontent.com/38421337/159483906-2efef386-a673-4189-9d82-e58fed23d0b6.mov
schema
```json
{
"anyOf": [
{
"prop": {
"const": "const value"
}
}
},
{
"prop": {
"const": "const value2"
}
}
},
{
"prop": {
"type": "boolean",
"default": false
}
}
},
{
"prop": {
"type": "null"
}
}
}
]
}
```
no ref
modified existing and add new
> fix: merge simple property completion

- src/languageserver/handlers/notificationHandlers.ts
- src/languageserver/handlers/settingsHandlers.ts
- test/settingsHandlers.test.ts
Changes the `SettingsHandler` and exposes only `pullConfiguration` as API. This makes it easy to keep a consistent Settings list which would otherwise be affected by multiple events causing race conditions.
Also modifies the tests to test through `pullConfiguration`.
fixes https://github.com/redhat-developer/vscode-yaml/issues/721
Added a new case to cover schema store and modified existing tests.
> Expose only pullConfiguration as API

- README.md
- src/languageserver/handlers/settingsHandlers.ts
- src/languageservice/services/yamlCompletion.ts
- src/languageservice/yamlLanguageService.ts
- src/yamlSettings.ts
- test/autoCompletion.test.ts
This functionality helps a less technical person not to get lost on completion when there are complicated schemas and many properties that can be used (see the last screen - there are too many options so the user should select the parent/skeleton first and don't have to care about all possible properties).
It little bit extends 'parent/skeleton' object completion.
This PR adds`yaml.selectParentSkeletonFirst`. If true, the user must select some parent skeleton first before autocompletion starts to suggest the rest of the properties.
When yaml object is not empty, autocompletion ignores this setting and returns all properties and skeletons.
Not sure if it's useful for your users but it can help others (less technical creators).
suggest only skeletons because object is empty:
whit disabled …
> Select parent skeleton first before other properties are suggested

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.test.ts
unify how codecompletion is displayed in this two situations:
- ` - #curstor`
- ` -#curstor`
current implementation:
https://user-images.githubusercontent.com/38421337/161982187-22b1a7c8-3e16-498d-abf4-9c1810997e45.mov
after this update:
https://user-images.githubusercontent.com/38421337/161982355-9bbd70cb-4caf-4abe-8ab8-3511af1fa4ab.mov
this PR extends:
https://github.com/redhat-developer/yaml-language-server/pull/696
https://github.com/redhat-developer/yaml-language-server/pull/697
but it's working separately 
modified existing unit tests
I also tested all 3 changes together. I didn't want to put it all together because it's quite different modifications.
> change completion that is invoked just after array symbol

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.test.ts
- test/autoCompletionFix.test.ts
fix array completion when the cursor is in the middle of the empty text
before:
https://user-images.githubusercontent.com/38421337/161768169-198a26ce-d30b-48f7-bd42-5dcf724a6468.mov
after:
https://user-images.githubusercontent.com/38421337/161768203-082356fc-063a-4dab-9f2c-4687594bb28a.mov
schema for this test
```yaml
"arrayObj": {
"type": "array",
"items": {
"item1": {
"type": "string"
},
"item2": {
"type": "string",
}
},
"required": [
"item1",
"item2"
]
}
},
```
no ref
added UT, 
modified existing one
> fix array completion in the middle of the empty text

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletionFix.test.ts
fix completion when the cursor is in the middle of the empty text
https://user-images.githubusercontent.com/38421337/161766640-d52a9a27-5156-4ad9-abc4-234c1bf1f04c.mov
no ref
added UT
> fix: completion in the middle of the empty text

- src/languageservice/services/yamlFolding.ts
- test/yamlFolding.test.ts
Adds folding for multiline strings. Refactors the property folding logic. Adds a test for multiline strings.
Fixes https://github.com/redhat-developer/vscode-yaml/issues/737
Added unit test for multiline string folding
> Fix folding for multiline strings

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.test.ts
`value as string` in typescript is just `value` in javascript, so it's not really converted.
> fix value type convert to string

- src/languageservice/parser/yaml-documents.ts
- src/languageservice/parser/yamlParser07.ts
- test/yaml-documents.test.ts
Adds a fallback to default if yamlVersion is not set on the options. Adds a test and fixes API doc.
fixes #711
> ensure YAML version is set always before parsing

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletionFix.test.ts
add support for completion for an object that has a definition in `additionalProperties`
```
{
type: 'object',
additionalProperties: {
anyOf: [
{
type: 'string',
const: 'test1',
},
],
},
};
```
typescript that produces this schema:
```ts
Record<string, 'test1' | InterfaceXYZ>
```
no ref
add UnitTest
> fix: object with additional properties completion

- src/languageservice/parser/jsonParser07.ts
- test/autoCompletionFix.test.ts
This PR checks the enum values that matches started characters of node value on auto suggestions
https://github.com/redhat-developer/vscode-yaml/issues/705
Yes. With existing UT.
> Fixed auto complete even parameters not in the specific order

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.test.ts
_It improves core test infrastructure:_
While helping to fix several autocomplete bugs (eg #724) in the language server, it was difficult to understand where the "cursor" was placed in sample `content` within the `tests`. 
The existing code uses the following method signature, whereby the caller has to do the math on the `position` parameter to establish where the caret is placed:
```typescript
// Method
function parseSetup(content: string, position: number): ...
// Caller
const content = 'hello world this is great';
const completion = parseSetup(content, 10); // <---- Can you easily tell where the cursor is?
`
```
While this works, it is difficult to maintain since it's not easy to understand the test by just looking at the `content` (& without doing math)
This PR introduces the notion …
> fix: use virtual caret in tests

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletionFix.test.ts
Add the possibility to have code completion on properties of 'anonymous/unknown' object.
Example:
typescript:
```ts
object: Record<string,string>
```
will produce approximately this schema:
```json
"object": {
"additionalProperties": {
"type": "string"
}
}
```
then in the yaml it could be complicated for users to guest what can be inside the object
```yaml
object:
```
But jsonschema standard allows `propertyNames` element to extend properties [json schema doc](https://json-schema.org/understanding-json-schema/reference/object.html#property-names)
So by this PR, this schema:
```json
{
"additionalProperties": true,
"propertyNames": {
"title": "key of obj",
"description": "desc",
"markdownDescription": "*md description*"
}
}
```
will produce this result: …
> feat: add completion for additionalProperties propertyName

- README.md
Add's a link to nova-yaml to the extension readme
n/a
It's just a readme change
> Add nova-yaml to extension readme

- test/autoCompletion.test.ts
- test/autoCompletionFix.test.ts
- test/defaultSnippets.test.ts
- test/hover.test.ts
- test/integration.test.ts
- test/multipleDocuments.test.ts
- test/utils/testHelper.ts
This is a follow-up to #722
* The previous PR introduced the concept of a _virtual caret_. However, I only updated a few tests in order to keep the noise low so the reviewer could easily see what was going on.
* This PR updates all relevant/remaining tests to use the new functionality. Note that some tests are not updated, for example when they specify an index that is out of range (eg `parseSetup('abc', 10)`)
I improved the caret usage/algorithm to use "bookends" instead of absolute position. The previous method made it hard to specify some boundary cases.
- We now use caret "bookends" which surround the intended character, for example:
- `'a|b|c'` is the same as `position = 1`, ie the caret is on the `'b'` char
- `'ab| |'` is the same as `position = 2`, ie the caret is on the `' '` char …
> fix: update tests to use virtual caret

- src/languageservice/parser/yaml-documents.ts
- test/autoCompletionFix.test.ts
fix: completion invoke when next line has an indented comment
The change for this was to evaluate `range[1]` (value-end) rather than `range[2]` (node-end, which may contain trivia such as comments) when trying to find the closest node.
```yaml
example:
prop1: "test"
#comment
```
no ref
added unit tests
> fix: completion invoke when next line has an indented comment

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletionFix.test.ts
fix completion when property name is expected in nested object
```yaml
test2: 
pr # 1 worked ok here
test1:
nested: 
pr # 2 didn't work, this PR fixes this
```
this PR fixes the # 2nd scenario and add UT for the # 1st example
note that I am not sure if there could be more issues in other places where the root is modifying (`currentDoc.internalDocument.set`) instead of modifying `parent`. 
It seems that this part of the code is not under the UTs, so if I try to comment all `currentDoc.internalDocument.set...` all tests will pass. So I am afraid and won't change others because not sure what yaml is behind.
no ref
add UT for both examples
> fix: suggest prop of the object -based on not completed prop name

- src/languageservice/parser/yaml-documents.ts
- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.test.ts
- test/autoCompletionFix.test.ts
fix another situation with extra space after the current cursor.
My previous fixes covered only some of the possible situations (https://github.com/redhat-developer/yaml-language-server/pull/696, https://github.com/redhat-developer/yaml-language-server/pull/697)
there were still problems in this type of yaml (2nd position)
```yaml
array:
- prop1: val1
prop2: #__ (#cursor, _space)
```
```yaml
obj:
prop1: val1
prop2: #__ (#cursor, _space)
```
This fix will solve this situation (for object, arrays in one place) by finding the correct node inside `getNodeFromPosition`, instead of fixing it later and trying to find a better node (null node).
Another part of this PR is to overwrite range - remove extra space 
no ref
modified and added unit tests
> fix: extra space after position

- src/languageservice/utils/textBuffer.ts
- test/textBuffer.test.ts
My project uses `yaml-language-server`, and I got these errors in Sentry:
```
Error: Range#create called with invalid arguments[1682, -1, 1682, 0]
4    at Object.e.create
5  at Object.e.create
6  at Zl.getLineCharCode
```
Unfortunately, I wasn't able to reproduce this error, so all my work is just following the stacktrace.
The only place where the function `getLineCharCode` is used is here:
https://github.com/redhat-developer/yaml-language-server/blob/eae5206655503a59023abed1713f4623ea1bd93d/src/languageservice/utils/indentationGuesser.ts#L136-L138
Both surrounding code and description on `charCodeAt` suggest that this index should be 0-based, but the `getLineCharCode` is written with a 1-based index in mind, which seems like the source of this bug.
I wasn't able to reproduce the original …
> fix: zero-based index

- src/languageservice/parser/yaml-documents.ts
- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.test.ts
- test/autoCompletionFix.test.ts
Overwrite the range if the current line has trailing spaces.
this PR is based on PR #732 
- that one fixed values with trailing spaces
but this one fixes properties with trailing spaces
note: it will be better to finish #732 and then this one, but it should be ok to just take this PR, because it includes all from 732.
```yaml
object:
na#__ (#cursor, _space)
```
gives wrong code-completion range
no ref
added unit tests
> fix: partial key with trailing spaces + PR#732 changes

- package.json
- src/languageservice/services/yamlCodeLens.ts
- src/languageservice/services/yamlSchemaService.ts
- src/languageservice/utils/schemaUtils.ts
- test/schemaValidation.test.ts
- yarn.lock
It add JSON Schema validation with [ajv](https://ajv.js.org/) lib.
It allows to show errors in scheme instead of wrong errors during yaml validation, like https://github.com/redhat-developer/vscode-yaml/issues/788
> Note: it also upgrades TS version, as latest `ajv` requires newer TS version
Fixes: https://github.com/redhat-developer/vscode-yaml/issues/788
with tests
> Add JSON Schema validation

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletionFix.test.ts
This PR adding double quotes to the number when enum type is string and it has number variable on it. 
Ex: "enum": ["12.1", "13.0", "13.1", "14.0", "all"]
https://github.com/redhat-developer/yaml-language-server/issues/709
Yes, added UT
> Fix auto complete enum string with quote on number

- src/languageservice/services/yamlCompletion.ts
- test/defaultSnippets.test.ts
- test/fixtures/defaultSnippets.json
When choosing a snippet to auto-complete within an array, the indentation level was wrong on the lines below the insertion point.
```yaml
example:
- #cursor here
```
would auto-complete to:
```yaml
example:
- item1: "some item"
item2: "another item"
```
rather than:
```yaml
example:
- item1: "some item"
item2: "another item"
```
no ref
Manual tests as well as new unit test.
> fix: proper indenting of snippet within an array

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletionFix.test.ts
This PR skips the sibling object suggestion when the other object has its value
https://github.com/redhat-developer/yaml-language-server/issues/664
Yes and added UT
> skip sibling object when object has colon

- src/languageservice/parser/jsonParser07.ts
- test/schemaValidation.test.ts
This PR resolves the `i.startsWith is not a function` issue in telemetry
https://github.com/redhat-developer/yaml-language-server/issues/747
Yes with existing UT and added UT for current scenario.
> check string type or not for value as well

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletionFix.test.ts
Fixes an issue where the indent is incorrect for an object within an array that is also within an array.
Given the following schema:
```json
{
"array1": {
"type": "array",
"items": {
"required": ["thing1"],
"thing1": {
"required": ["array2"],
"array2": {
"type": "array",
"items": {
"required": ["thing2", "type"],
"type": {
"type": "string"
},
"thing2": {
"required": ["item1", "item2"],
"item1": { "type": "string" },
"item2": { "type": "string" }
}
}
}
}
}
}
}
}
}
}
}
}
```
When autocomplete is attempted on:
```yaml
array1:
- #cursor here
```
It previously autocompleted to:
```yaml
array1:
- thing1:
array2:
- type: …
```
> fix: autocomplete indent on object within an array

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletionFix.test.ts
Fixes an indentation issue when you have trailing spaces after the hyphen.
Given the schema:
```yaml
{
type: 'object',
properties: {
test: {
type: 'array',
items: {
type: 'object',
properties: {
objA: {
type: 'object',
required: ['itemA'],
properties: {
itemA: {
type: 'string',
}
}
}
}
}
}
}
}
```
The following yaml:
```yaml
test:
- #________(# = cursor, _ = spaces)
```
Would be autocompleted to:
```yaml
test:
- objA:
itemA: 
```
After the fix it autocompletes to:
```yaml
test:
- objA:
itemA: 
```
no ref
Manual and unit test.
> Fix indentation with extra spaces after cursor.

- src/languageservice/services/yamlHover.ts
- test/hover.test.ts
This PR append the title and description of anyOf schemas while hover
https://github.com/redhat-developer/vscode-yaml/issues/784
Yes. added UT
> append the title and description of anyOf schemas while hover

- src/languageservice/services/yamlHover.ts
- test/hover.test.ts
- test/schemaValidation.test.ts
This PR append the title and description of anyOf schemas while hover
https://github.com/redhat-developer/vscode-yaml/issues/784
Yes. added UT
> merged the hover results

- .github/workflows/CI.yaml
- .github/workflows/release.yaml
- package.json
- src/languageservice/parser/jsonParser07.ts
- src/server.ts
- tsconfig.json
- yarn.lock
Also changes the eslint version to be compatible with typescript 4.8.  Fixes a few eslint errors due to this change.
Updates CI and release/
Tested with Unit tests
> Update to nodejs 16 and typescript 4.8

- src/languageservice/services/yamlCompletion.ts
- src/languageservice/utils/schemaUtils.ts
- test/autoCompletion.test.ts
- test/autoCompletionFix.test.ts
- test/fixtures/testArrayCompletionSchema.json
- fix array nested structure
- the previous implementation didn't go deeper into nested schemas (nested anyof)
- unify array item value completion
- there were three almost identical implementation 
schema:
```json
"test_array_nested_anyOf": {
"items": {
"anyOf": [
{
"anyOf": [
{
"$ref": "#/definitions/obj1"
},
{
"$ref": "#/definitions/obj2"
}
]
},
{
"$ref": "#/definitions/obj3"
}
]
},
"type": "array"
}
```
```yaml
test_array_nested_anyOf:
```
gives only two items:
1st for `anyOf`
2nd for `obj3`
The nested array item structure is flattened
note that without `- obj1: null` in screenshots YLS doesn't know that we are in an array and won't give any results
no ref
add UT and modify existing
> fix: completion nested array item to flat structure

- src/languageservice/parser/jsonParser07.ts
- test/schemaValidation.test.ts
- test/utils/verifyError.ts
When problem `'Property {0} is not allowed.'` is found during diagnostic it will extend `diagnostic.data` by possible props that could be inside the object.
- `diagnostic.data = Object.keys(schema.properties) subtract seenProperties`
then it can be used inside `CodeAction` to suggest proper properties instead of the wrong one.
no ref
added tests
> feat: add diagnostic data with missing properties

- src/languageservice/jsonSchema.ts
- src/languageservice/parser/jsonParser07.ts
- src/languageservice/parser/yaml-documents.ts
- src/languageservice/services/yamlCompletion.ts
- src/languageservice/services/yamlValidation.ts
- test/autoCompletion.test.ts
- test/schemaValidation.test.ts
this PR adds the ability to extend 'schema if condition' with `filePatternAssociation`. it means that it's possible to extend if condition to be connected to some yaml filename.
basically, it's something similar to `yamlValidation: [{filematch, url}]` to find whole schema based on yaml filename, but this feature is for finding subschema based on the yaml name.
I added this because my schemas are dynamically created and I need some small modifications inside the schema based on the filename. 
```js
{
type: 'object',
title: 'basket',
properties: {
name: { type: 'string' },
},
if: {
filePatternAssociation: '*fruit.yaml',
},
then: {
properties: {
pineapple: { type: 'string' },
},
required: ['pineapple'],
},
else: {
properties: {
carrot: { type: 'string' },
},
required: ['carrot'],
},
}
``` …
> feat: add if filePatternAssociation

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletionFix.test.ts
This PR resolved code completion issue when added array items based on schema
https://github.com/redhat-developer/yaml-language-server/issues/793
Yes. Tested with existing UT and added UT for mentioned scenario.
> fixed indentation issue on array object

- src/languageserver/handlers/settingsHandlers.ts
- src/languageserver/telemetry.ts
- src/languageservice/services/documentSymbols.ts
- src/languageservice/services/yamlCodeLens.ts
- src/languageservice/services/yamlCompletion.ts
- src/languageservice/services/yamlDefinition.ts
- src/languageservice/services/yamlHover.ts
- src/languageservice/services/yamlLinks.ts
- src/languageservice/services/yamlValidation.ts
- src/languageservice/telemetry.ts
- src/languageservice/utils/schemaUrls.ts
- src/languageservice/yamlLanguageService.ts
- src/server.ts
- src/webworker/yamlServerMain.ts
- src/yamlServerInit.ts
- test/settingsHandlers.test.ts
- test/telemetry.test.ts
- test/utils/testsTypes.ts
- test/yamlCodeLens.test.ts
- test/yamlDefinition.test.ts
In `monaco-yaml` I’m interested in stubbing the Telemetry option. However, currently everywhere this is used uses a type annotation based on the class. This means the implementation must match this class, including private properties. By accepting an interface instead, it’s possible to pass alternative implementations.
https://github.com/remcohaszing/monaco-yaml/issues/190
By running `tsc`.
> Make Telemetry an interface

- README.md
- src/languageservice/services/yamlSchemaService.ts
- src/languageservice/yamlLanguageService.ts
- test/schema.test.ts
Problem:
- Right now, when a file is watched by the registerContributor API a user has no way of overriding that schema. In certain cases, a user may want to override the schema provided by the registerContributor API on a file by file basis.
Solution:
- Make the modeline become a higher priority then the registerContributor API. That way users have the ability to always override the schema for the given file.
https://github.com/aws/aws-toolkit-vscode/issues/3012
> feat(modeline): Modeline takes precendence over registerContributor API

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletionFix.test.ts
fix range position with unfinished value completion with trailing spaces
https://user-images.githubusercontent.com/38421337/213417164-99b35c7f-0193-4ec8-8512-7bc5d90f0d2b.mov
https://user-images.githubusercontent.com/38421337/213417241-cdb0081e-764b-4236-9b95-254124dfb1ea.mov
no ref
added similar unit tests to 'partial key' tests
> fix: value completion with trailing spaces

- CHANGELOG.md
- README.md
- package.json
- src/languageserver/handlers/settingsHandlers.ts
- src/languageservice/services/validation/map-key-order.ts
- src/languageservice/services/yamlCodeActions.ts
- src/languageservice/services/yamlValidation.ts
- src/languageservice/yamlLanguageService.ts
- src/yamlSettings.ts
- test/settingsHandlers.test.ts
- test/utils/serviceSetup.ts
- test/yamlCodeActions.test.ts
- test/yamlValidation.test.ts
- yarn.lock
Introduces a new setting `yaml.keyOrder` that enforces the alphabetical key order for mappings when set to true. 
In addition to validation, it also provides a code action to fix the order for the map
https://github.com/redhat-developer/vscode-yaml/issues/95
Adds tests for validation, new settings and code action
> Map key order

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.test.ts
fix the completion item range when yaml contains a word ending with a dash symbol.
https://user-images.githubusercontent.com/38421337/212872479-136c433b-9588-4c7c-a3d9-747a64af719d.mov
I removed the piece of code that caused this problem (all existing tests passed after removing it).
To be honest I am not sure why this code was there. I tried to think about but I wasn't able to find a scenario when is needed to subtract one character if the current position contains `-`
note that this example didn't use removed piece of code
```yaml
array:
-
```
no ref
added test
> fix: completion value with dash

- .github/workflows/CI.yaml
- .github/workflows/release.yaml
Hi!
Following the [GH Action Security Hardening](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions) guide we should use the commit SHA instead of the `branch` or `tag` for any third-party untrusted action.
This PR was submitted by a script.
> Pin 3rd-party actions to SHA1

- src/languageservice/parser/jsonParser07.ts
- test/schemaValidation.test.ts
The existing [PR](https://github.com/redhat-developer/yaml-language-server/pull/802) has some issues due to my local reabase, Hence created a new one
Added IPv4 and IPv6 format validation on parser
https://github.com/redhat-developer/vscode-yaml/issues/832
Yes added UT
> added ipv4 and ipv6 validation

- README.md
Adds a README section covering the ability to use URL fragments to reference components of existing schemas.
Documents an existing feature that allows one to support components of existing schemas while maintaining [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).
I've tested this feature with inline configuration, using circleciconfig as an example, e.g.:
```yaml
```
I haven't *actually* tested it with server-side configuration yet, partially because the path-based association is kind of weak (`/src/jobs/*.yml` + `/src/jobs/*.yaml`)
1. Is there good documentation somewhere on how schemastore schemas work? It took me a while to figure out how to reference the schema for an individual circleci job (i.e. `additionalProperties`)
2. Should the documentation use an example other …
> Document url fragment references

- .vscode/launch.json
- src/languageservice/services/yamlHover.ts
- test/hover.test.ts
- test/integration.test.ts
- test/multipleDocuments.test.ts
This PR shows the description without escape sequence char even description has indentation on hover
https://github.com/redhat-developer/vscode-yaml/issues/886
Yes. Added UT
> replace multiple space into single space on markdown text in hover

- src/languageservice/services/validation/unused-anchors.ts
- test/yamlValidation.test.ts
Fixes broken warnings on unused anchors inside an array:
Test case included in PR.
> Fix anchor diagnostics

- src/languageservice/parser/yaml-documents.ts
- src/languageservice/services/yamlCompletion.ts
Adds a new API to update the internal AST from the internal document without requiring re-assigning the internal document.
Fixes eslint issues about self-assigning 
> Add API to update AST tree from internal document

- src/languageservice/utils/schemaUtils.ts
- test/autoCompletion.test.ts
- test/schemaValidation.test.ts
This PR shows schema type when mismatch error along with it title
https://github.com/redhat-developer/yaml-language-server/issues/845
Yes. Added UT
> 845 type errors inform wrong type when parent schema has keyword title

- CHANGELOG.md
They were showing as subheadings to `0.12.0`.
Fixes heading levels for versions older than `0.12.0` in the readme.
Was noticeable in the ToC.
> Fix older readme heading levels

- src/languageserver/handlers/schemaSelectionHandlers.ts
- src/languageservice/services/documentSymbols.ts
- src/languageservice/services/yamlCodeLens.ts
- src/languageservice/services/yamlCompletion.ts
- src/languageservice/services/yamlDefinition.ts
- src/languageservice/services/yamlHover.ts
- src/languageservice/services/yamlLinks.ts
- src/languageservice/services/yamlValidation.ts
- src/languageservice/yamlLanguageService.ts
- src/yamlServerInit.ts
- test/yamlLanguageService.test.ts
Some of the functionality currently exposed by the language service doesn't make sense when running the language service as a library rather than through the language server. This PR seeks to clean up some of those cases by marking connection, telemetry, and yamlSettings as optional
None
Tested by running `npm run test` and then ensuring that VSCode-YAML works with these changes
> refactor(language service): Clean up the language service interface

- src/languageserver/handlers/settingsHandlers.ts
Marks settings readonly to avoid any regressions in the future
None
> Mark settings readonly

- package.json
- src/languageservice/parser/jsonParser07.ts
- src/languageservice/services/yamlValidation.ts
- src/languageservice/utils/astUtils.ts
- src/languageservice/utils/textBuffer.ts
- src/yamlServerInit.ts
- test/autoCompletion.test.ts
- test/autoCompletionFix.test.ts
- test/code-action-schema.test.ts
- test/integration.test.ts
- test/settingsHandlers.test.ts
- test/yamlCodeLens.test.ts
- test/yamlCommands.test.ts
- yarn.lock
Updates prettier to 2.8.7. Fix the problems with the lint rules that were introduced with this release
https://github.com/redhat-developer/vscode-yaml/issues/255
> Update prettier version

- test/hover.test.ts
- test/integration.test.ts
The previous behavior for hover replaces indentations with the `&emsp;` entity, because Markdown treats whitespace at the beginning of a line in a special way. However, when the indentation setting wasn't set, the regex that does that replace was set to empty (`""`) and so would include an `&emsp;` entity between every character.
This went under the radar because the previous PR #844 also changed the tests setup to include a `.withIndentation` call, which made sure all tests were passing.
In this PR I'm reverting that to the default behavior for most tests, but overriding the default only on the test introduced in #844.
The issue is referenced on a comment of PR #844. [here](https://github.com/redhat-developer/yaml-language-server/pull/844#issuecomment-1480559728)
I have tested this fix …
> fix(indentation): hover behavior when indentation not set

- src/languageserver/handlers/languageHandlers.ts
- src/languageservice/services/yamlSelectionRanges.ts
- src/languageservice/yamlLanguageService.ts
- src/yamlServerInit.ts
- test/yamlSelectionRanges.test.ts
Add selection ranges support
https://github.com/redhat-developer/yaml-language-server/assets/68118705/d9534494-2ab4-4993-85b6-94c54410380b
There're some problems about selecting single word caused by [this](https://github.com/redhat-developer/vscode-yaml/blob/b72e1b7146baa97a4f28499a01eb0d4e64a19876/language-configuration.json#L37)
I don't know what that regex actually does so I can't really fix it
[vscode-yaml#307](https://github.com/redhat-developer/vscode-yaml/issues/307)
> Add selection ranges support

- src/languageservice/services/yamlSchemaService.ts
- test/autoCompletion.test.ts
- test/autoCompletionFix.test.ts
- test/code-action-schema.test.ts
- test/hover.test.ts
- test/schemaValidation.test.ts
- test/utils/testHelper.ts
Introduces a new CustomSchemaProvider. Removes the earlier hack from SchemaService that mapped schemas to itself. Updates the tests for the new API.
- Fixes #871.
- Fixes redhat-developer/vscode-yaml/issues/894.
The existing unit tests are modified to work with these changes.
> CustomSchemaProvider for tests

- src/languageservice/parser/jsonParser07.ts
- src/languageservice/utils/objects.ts
- test/schemaValidation.test.ts
fix validation of nested `anyOf` consts
schema:
```json
{
"options": {
"anyOf": [
{
"form": {
"type": "string"
},
"provider": {
"type": "string",
"const": "test1"
}
},
"required": [
"form",
"provider"
]
},
{
"form": {
"type": "string"
},
"provider": {
"anyOf": [
{
"type": "string",
"const": "testX"
}
]
}
},
"required": [
"form",
"provider"
]
}
]
}
}
}
```
will produce this error:
https://github.com/redhat-developer/yaml-language-server/assets/38421337/8524d0ea-5adf-453a-bbe4-e42a3464c4d8
note that 'missing form property' is necessary to trigger the bug (there has to be some problem in both subSchemas)
order of the object in `anyOf` is also important
no existing issue
unit test
> fix: nested anyof const

- src/languageserver/handlers/languageHandlers.ts
- src/languageservice/services/yamlCodeLens.ts
- src/languageservice/services/yamlFormatter.ts
- src/languageservice/yamlLanguageService.ts
- src/yamlSettings.ts
Some parameters are optional, but were marked as required.
Language service methods were marked as bound methods, but they don’t have to be called as such.
The `Thenable` type from `json-rpc` was used. These were replaced with the builtin TypeScript type `PromiseLike`.
N/A
```sh
tsc
```
> Fix some small type issues

- README.md
This adds [`volar-service-yaml`](https://github.com/volarjs/services/tree/master/packages/yaml) to the list of integrations. This makes it possible to integrate `yaml-language-server` for YAML embedded in other text documents, such as markdown frontmatter.
N/A
Clicked the link to make sure it’s correct.
> Add volar-service-yaml to clients

- README.md
Atom has been sunset. The link is no longer available.  Clicking the link would take the user to a GitHub blog post about this instead.
N/A
Clicking the removed link.
> Remove ide-yaml from known clients

- src/languageservice/services/yamlHover.ts
- test/hover.test.ts
This PR updates the hover service to display all possible enum values, rather than just the currently selected one. Additionally, it will display the enums regardless of whether the schema contains explicit descriptions (though it will continue to display the descriptions if present - see included test case).
<br />
<br />
Also: 
- Included a minor change to how examples are displayed (i.e. added markdown bullets) to make them visually consistent with the enums.
- Added a `ensureLineBreak` helper to make sure there is consistent spacing between each of the various hover sections.
Fixes #941
- Tested locally with https://github.com/twelvelabs/stamp/blob/main/docs/stamp.schema.json
- See test cases in `test/hover.test.ts`
> fix: show all enums on hover

- README.md
All JSON is YAML, but no the other way around.
Fix syntax highlighting in the README.
Closes #944 
See the rendering: [here](https://github.com/pierreprinetti/yaml-language-server/blob/readme_set_yaml_on_examples/README.md).
> README: Fix syntax highlighting

- src/languageservice/services/yamlHover.ts
- test/hover.test.ts
This MR improves the rendering of examples on hover by:
1. Rendering the examples as YAML rather than JSON.
2. Adding an info string to the [fenced code block](https://github.github.com/gfm/#fenced-code-blocks) so that the examples are properly syntax highlighted. According to the LSP spec, [markdown content should be expected to be GFM](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#markupContent), so this shouldn't be an issue for clients.
3. Moving the indentation escaping logic to `toMarkdown`, so that we only escape non-markdown strings. Currently the escaping is done on the entire hover content, regardless of whether that content contains actual markdown. This change also fixes a bug where intentional indentation in `markdownDescription` …
> fix: render examples as yaml on hover

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.test.ts
- test/autoCompletionFix.test.ts
unify string text inserting for array and property
when you choose string property from completion you get
`na` -> `name: `
but for array, it generated extra quotes:
`arr` -> 
```
array:
- ""
```
These extra quotes caused, that it wasn't possible to invoke completion just after the code insert, but you had to delete `""` continue...
the behavior is just a little bit different than for property text inserting.
https://github.com/redhat-developer/yaml-language-server/assets/38421337/8d73fb4a-8b10-49d9-ac27-ac37362d89c4
Note that I didn't change it for `number` nor for `bool` because it seems to me a little bit different scenario
update current tests
> feat: unify string insert text for array and property

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletionFix.test.ts
fixes issue where `additionalProperties` were ignored on value completion if the object schema contains `properties`
check the test and code fix, it's more descriptive probabbly
extends on of the previous fix https://github.com/redhat-developer/yaml-language-server/pull/717
adds test
> fix: snippets in additionalProperties

- src/languageservice/services/yamlSelectionRanges.ts
- src/languageservice/yamlLanguageService.ts
- test/yamlSelectionRanges.test.ts
- tsconfig.json
Improve some special cases for selection ranges support
Before
https://github.com/redhat-developer/yaml-language-server/assets/68118705/3b998413-ef30-4849-b213-98c8ca0d204c
After
https://github.com/redhat-developer/yaml-language-server/assets/68118705/ef1570c0-442c-4948-bd3f-761ab91b9b64
> Improve some special cases for selection ranges

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletion.test.ts
Add null check for `customTags` setting, so if the setting is not set completion will not fail.
Fixes #807
I added an integration test.
> Add null check for `customTags`

- src/languageserver/handlers/settingsHandlers.ts
When the url property in the schema store is undefined the program crashes. It should also be considered adding some useful logging. Enabling schemastore without an url doesnt seem to do much.
I couldnt find any issues referencing this. I can make one if thats wanted
Tested it locally. Try installing the package and running it with yaml.schemastore.enabled = true without specifying an url. After adding the `?` it wont crash anymore
1. setConfiguration
`[ERROR][2024-03-15 22:13:53] ...lsp/handlers.lua:535	"TypeError: Cannot read properties of undefined (reading 'length')\n    at SettingsHandler.setConfiguration (C:\\Users\\User\\AppData\\Roaming\\npm\\node_modules\\yaml-language-server\\out\\server\\src\\languageserver\\handlers\\settingsHandlers.js:80:43)\n    at …
> fix: crash when url is undefined

- CHANGELOG.md
Updated changelog for the release 1.15.0
NA
NA
> changelog updated for the release 1.15.0

- package.json
- test/utils/testsTypes.ts
- yarn.lock
Update `vscode-languageserver` to version 9.
N/A
```sh
npm test
```
> Update to vscode-languageserver 9

- package.json
- src/languageserver/handlers/languageHandlers.ts
- src/languageserver/handlers/requestHandlers.ts
- src/languageserver/handlers/validationHandlers.ts
- src/languageserver/handlers/workspaceHandlers.ts
- src/languageservice/parser/jsonParser07.ts
- src/languageservice/services/documentSymbols.ts
- src/languageservice/services/yamlCodeLens.ts
- src/languageservice/services/yamlFormatter.ts
- src/languageservice/services/yamlHover.ts
- src/languageservice/services/yamlValidation.ts
- src/languageservice/utils/schemaUtils.ts
- src/languageservice/yamlLanguageService.ts
- test/formatter.test.ts
- yarn.lock
This updates Prettier to version 3.
- Prettier 3 is async, so related functions were made async.
- Code was reformatted using Prettier.
- Prettier now ships their own types, so `@types/prettier` was removed.
- Prettier was moved to `dependencies`. `optionalDependencies` is for dependencies that have a `install` script that may fail. This isn’t the case for Prettier.
- `eslint-plugin-prettier` was updated as well.
Alternatively the formatting functionality could be removed. IMO people should just use Prettier themselves for formatting YAML instead of relying on this `yaml-language-server`.
N/A
```sh
npm test
```
> Update to Prettier 3

- src/languageservice/utils/schemaUrls.ts
- test/autoCompletionFix.test.ts
- test/integration.test.ts
- test/schema.test.ts
updates the bundled kubernetes json schema to 1.32.1, fixing some tests that relied on the 1.22.4 schema.
none
integration tests pass.
> k8s: update schema to 1.32.1

- src/languageservice/services/yamlHover.ts
- test/hover.test.ts
Currently, descriptions directly associated with anyOf fields are not shown when hovering. This PR ensures that descriptions for anyOf fields do not only show the descriptions of their children but also the parent description.
fixes https://github.com/redhat-developer/yaml-language-server/issues/952
Yes, please see the modified unit test files.
> add missing field descriptions for anyOf

- src/languageserver/handlers/settingsHandlers.ts
- src/languageserver/telemetry.ts
- src/languageservice/services/documentSymbols.ts
- src/languageservice/services/yamlCodeLens.ts
- src/languageservice/services/yamlCompletion.ts
- src/languageservice/services/yamlDefinition.ts
- src/languageservice/services/yamlHover.ts
- src/languageservice/services/yamlLinks.ts
- src/languageservice/services/yamlValidation.ts
- src/languageservice/telemetry.ts
Every call to `telemetry.sendError` contained the same boilerplate code to create an object with the property `error`, which contains a string representation of the real error. This change moves this conversion into the `Telemetry` implementation. This reduces the need for boilerplate code in other places.
This change also affects `monaco-yaml`. Because the telemetry now resolves the real error, the browser can log the error to the console with a better stack trace.
```sh
npm test
```
> Send real errors to telemetry

- src/languageservice/services/yamlHover.ts
- test/hover.test.ts
fix enum values to be unique:
* when several schemas get combined (e.g., `oneOf`, `anyOf`) the available values for an `enum` could get merged
* this could lead to enum values present several time
* this PR only adds an enum values to the merged list, if its value is not present so far
* corresponding unit test is present as well
example:
schema:
```json
{
"animal": {
"description": "should return this description",
"anyOf": [
{
"enum": [ "cat", "dog", "non" ],
"enumDescriptions": [ "", "Canis familiaris" ]
},
{
"enum": [ "bird", "fish", "non" ],
"enumDescriptions": [ "", "Special fish" ]
}
]
}
}
}
```
Without the fix the `available value` list is: `[ cat, dog, non, bird, fish, non ]` with `non` being present twice.
With the fix the second `non` is …
> fix enum values to be unique

- src/languageservice/services/yamlFormatter.ts
The import from `prettier` includes support for all languages supported by Prettier. The `prettier/standalone` import only includes the core. The `prettier` export also points to `prettier/standalone` for the `browser` export condition.
This means that with this change `yaml-language-server` has to load less code, leading to faster startup time. And depending on configuration, it may lead to smaller bundle sizes.
This PR is an improvement, but I would strongly prefer #983.
`npm test`
> Import Prettier from prettier/standalone

- src/languageservice/parser/jsonParser07.ts
- src/languageservice/utils/math.ts
- test/jsonParser.test.ts
In the case of float numbers the multipleOf is not calculated accurately because of the floating point math used in JavaScript. This PR adds a function which does a float safe remainder operation. The remainder in the multipleOf logic is replaced by this function.
Ref #985 
Added test `multipleOfFloat`
> multipleof does not work for floats

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletionFix.test.ts
This PR suggest characters with escape chars if needed
https://github.com/redhat-developer/vscode-yaml/issues/1097
Yes added test case for the fix
> fix for auto completion with escape sequence chars

- src/languageservice/parser/jsonParser07.ts
- test/autoCompletionFix.test.ts
- test/schemaValidation.test.ts
improve compare mechanism that should choose correct schema alternatives
fixes this issue https://github.com/redhat-developer/yaml-language-server/issues/684
replces this PR https://github.com/redhat-developer/yaml-language-server/pull/759
added tests
> fix: anyOf compare alternatives

- src/languageservice/parser/jsonParser07.ts
- test/schemaValidation.test.ts
suggested properties are filtered out if the schema contains doNotSuggest or  deprecationMessage
this PR does the same for `possibleProperties` in validation error
no ref
adds unit test
> fix: exclude not suggest properties from possible properties error

- src/languageservice/services/yamlCompletion.ts
- test/autoCompletionFix.test.ts
Small fix/improvement of propertyNames suggestion if `doNotSuggest` or `deprecationMessage` is set.
This suggestion should be excluded.
no ref
Adds unit test
> fix: do not suggest propertyNames if doNotSuggest is true

- CHANGELOG.md
[Changelog](https://github.com/redhat-developer/yaml-language-server/blob/main/CHANGELOG.md) updated for the release 1.18.0
No Ref
NA
> updated changelog for the release-1.18.0

- src/languageservice/services/validation/unused-anchors.ts
- test/utils/verifyError.ts
- test/yamlValidation.test.ts
fixes [#1098](https://github.com/redhat-developer/vscode-yaml/issues/1098)
This PR showed diagnostic error when there were no alias
https://github.com/redhat-developer/vscode-yaml/issues/1098
Yes added test case for the fix
> showed error on unresolved alias

- src/languageservice/services/yamlCodeActions.ts
- test/yamlCodeActions.test.ts
Fixes the error message that the code action provider expects so that the quickfix is generated once more. 
I think the error message changed when switching validators. There is nothing more concrete (such as a diagnostic code) to identify the "indentation cannot be tabs" diagnostics.
Fixes #1052
I've updated the unit tests. Perhaps an integration test would be helpful to avoid something similar happening in the future? I'd like a second opinion in this.
> Fix "convert tabs to space" quickfix for "indentation cannot be tabs"

- package.json
- src/languageserver/handlers/settingsHandlers.ts
- src/languageservice/services/yamlFormatter.ts
- src/languageservice/yamlLanguageService.ts
- src/yamlSettings.ts
- test/formatter.test.ts
- yarn.lock
Adds the 'yaml.format.trailingComma' to the formatter.
This option is available in prettier so implementing it is trivial. Needs the 'estree' prettier plugin, which is responsible for formatting JSON. As a result, this might increase the size of the language server.
eg. in the following, when 'yaml.format.trailingComma` is set to `false`, the last comma should be removed:
```yaml
{
key: 'value',
food: 'raisins',
airport: 'YYZ',
lightened_bulb: 'illuminating',
}
```
See redhat-developer/vscode-yaml#1112
Unit tests
> Add option to remove trailing comma

- src/yamlServerInit.ts
Some clients, like Neovim, do not support dynamic registration of formatting and range formatting. In this case, to tell the client that formatting is supported, the response to `initialized`, which contains the `ServerCapabilities`, should mark formatting and range formatting as supported.
Fixes #1031
Tried it out in Neovim, it's working after this patch.
> Support statically registering format support

- package.json
- yarn.lock
I noticed the version of ajv listed as a dependency was published three years ago. Bumped the version, and all tests still pass.
> Bump ajv version

- src/languageserver/handlers/settingsHandlers.ts
This PR will make `vscode-yaml` as  default formatter for `docker compose` and `github actions`. Will do one more PR on client side as well
https://github.com/redhat-developer/yaml-language-server/issues/1071
Yes with existing case
> added docker compose and GITHUB actions in setting handler

- src/languageservice/services/yamlSchemaService.ts
- test/yamlSchema.test.ts
Fix a bug where YAML files containing a JSON Schema that start with %YAML 1.x or a comment that contains a number would fail to to be parsed.
This is caused by the fact that the JSON Schema parser would contain the number, e.g. 1.2 as the value of `unresolvedJsonSchema.schema` and so the test for `=== undefined` would fail. This would cause the error from the JSON parser to be returned instead of trying to parse the file as a YAML file.
To work around this, also check if `unresolvedJsonSchema.schema` is a number. It if is, it clearly was not a JSON Schema and so we can safely try to parse the file as a YAML file.
Fixes: https://github.com/redhat-developer/yaml-language-server/issues/922
The modified test failed before the code change and passes after.
> Fix YAML JSON Schema files starting with %YAML 1.x

- package.json
- src/languageservice/services/yamlSchemaService.ts
- test/schemaValidation.test.ts
- yarn.lock
This helps to support the schema for openapi 3.0.0, among others, that use an older draft of JSON schema that has some type differences that make it incompatible with JSON schema draft 07.
See #1006 , the root cause for the issues that PR caused is that some schemas reference the metaschema using `https`, eg. `https://json-schema.org/draft-07/schema#`, which is invalid according to the spec. This PR suppresses this error, because in practice many schemas use `https` for the metaschema reference, and that shouldn't prevent validation of the YAML document.
~~- [ ] __TODO:__  Instead, we should provide a warning letting the user know about the `https` issue in the schema so they can fix the schema or file an issue to get the schema fixed.~~ I feel like we should do this in a separate PR, …
> Support draft-04 schemas

- src/languageservice/parser/ast-converter.ts
- test/yamlParser.test.ts
Currently, the code to convert AST nodes (in particular, resolve aliases) uses a recursive bit of code that will traverse through YAML aliases to resolve properties. For example:
```yaml
a: &a
name: "foo"
b: 
<<: *a
```
Parsing this code will produce two objects `a` and `b` that both have `name: "foo"`. The code that implements this alias resolution will only traverse to a depth of 1000, meaning it will give up on resolving aliases once it's traversed a really really long way down a path. This 1000 is very unlikely in human readable yaml files.
However, if you have a very large yaml files with many aliases, none of which come close to the `depth>1000` case, you can still experience errors due to a bug in the recursion. 
Internally we use the https://github.com/redhat-developer/vscode-yaml …
> Fix recursion bug in ast-conversion

- package.json
Moves @vscode/l10n to runtime dependencies.
From my Neovim lsp.log:
```
[ERROR][2025-07-10 13:40:08] ...p/_transport.lua:36 "rpc" "yaml-language-server"  "stderr"  "node:internal/modules/cjs/loader:1404\n  throw err;\n  ^\n\nError: Cannot find module '@vscode/l10n'\nRequire stack:\n- /usr/lib/node_modules/yaml-language-server/out/server/src/languageservice/services/yamlSchemaService.js\n- /usr/lib/node_modules/yaml-language-server/out/server/src/languageservice/yamlLanguageService.js\n- /usr/lib/node_modules/yaml-language-server/out/server/src/yamlServerInit.js\n- /usr/lib/node_modules/yaml-language-server/out/server/src/server.js\n- /usr/lib/node_modules/yaml-language-server/bin/yaml-language-server\n    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)\n    at …
```
> @vscode/l10n is a runtime dependency

- .github/workflows/release.yaml
> Fix auth on npm publish

- package-lock.json
- package.json
Fixes #1108
Remove `coveralls` as a developer dependency
From my understanding, we just need the coveralls GitHub Action in order for things to work.
`coveralls` is not used anywhere, so removing it should reduce the size of `./node_modules` for people developing yaml-language-server.
Also, `coveralls` might get flagged as a false positive security bug because it depends on `request`. By removing it, we won't get that false positive.
CI
> Remove coveralls dependency

- .github/workflows/CI.yaml
- .github/workflows/release.yaml
- setup-node@v5 creates a .npmrc if you provide a registry, so there should be no need to do that separately
- after setup-node@v5 is run, `npm publish` expects the token to be accessible from the environment variable `NODE_AUTH_TOKEN`
- also fix coveralls so that it only publishes results on ubuntu. If results are published from multiple platforms, then the 2nd and 3rd publish attempts will fail.
See https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#publish-to-npmjs-and-gpr-with-npm
This should fix the release GitHub Action (as well as the prereleases)
No, I don't think there's a good way to test it without merging first.
> Fix release GitHub Action

- README.md
> remove \n in README

- src/languageservice/services/yamlCodeActions.ts
- test/yamlCodeActions.test.ts
Wrapping code action title and textedit value with string in yamlCodeActions.ts
Fixes #1116 
Refer issue screenshots for the behavior before fix
After fixing the issue, behaviour is as follows in UI
Tested in UI
> Wrapping code action title with string
