src/languageService/services/documentSymbols.ts
src/languageService/services/yamlCompletion.ts
src/languageService/services/yamlHover.ts
src/languageService/services/yamlValidation.ts
src/languageService/utils/arrUtils.ts
src/server.ts
test/autoCompletion.test.ts
test/autoCompletion2.test.ts
test/documentSymbols.test.ts
test/hover.test.ts
test/hover2.test.ts
test/integration.test.ts
test/schemaValidation.test.ts
test/testHelper.ts

- Fixed issue where features weren't working in multi document yaml scenario
- Fixed the test cases to reflect this change
- Added new tests for multi document yaml

Fixed issue where features weren't working in multi document yaml scenario

---

src/server.ts

Fix for redhat-developer/yaml-language-server#33

Removed clientSnippetSupport field

---

src/languageservice/services/yamlCompletion.ts
src/server.ts
test/autoCompletion.test.ts
test/autoCompletion2.test.ts
test/autoCompletion3.test.ts

if there is no space between `-` and `holder`, the yaml structure will be wrong, so the array intellisense doesn't work

intellisense doesn't work for array item

---

src/languageservice/parser/scalar-type.ts
src/languageservice/parser/yamlParser.ts
test/schemaValidation.test.ts

This change was made over a month ago, but it was never released.
See redhat-developer/vscode-yaml#116

Fix for redhat-developer/vscode-yaml#116

---

package-lock.json
package.json

Update the vscode-uri dependency.
Fixes: https://github.com/redhat-developer/yaml-language-server/issues/110

Update vscode-uri dependency

---

src/server.ts

Fix for https://github.com/redhat-developer/yaml-language-server/issues/121

Added trigger characters

---

.vscode/launch.json
.vscode/tasks.json

Analogous to https://github.com/redhat-developer/vscode-yaml/pull/188
* Updated tasks.json to new task format for multi-root workspace support
* Accordingly updated launch.json and added clarifying comments like in client's launch.json

Update deprecated VSCode configuration

---

package-lock.json
package.json
tsconfig.json

Takes the tslint plugin for typescript into use.
Updatest the typescript version to 3.5.1
Signed-off-by: Gorkem Ercan <gorkem.ercan@gmail.com>

use tslint typescript plugin

---

src/server.ts
tslint.json

No code behaviour changes:
* Documented server.ts with comments for code clarity
* Used linter to annotate more types and fix string quote inconsistencies
* Added tslint whitespace rules and fixed whitespace inconsistencies
Should be functionally identical:
* Simplified onInitialize and schemaRequestService functions

Improve code clarity

---

src/languageservice/parser/jsonParser07.ts
test/integration.test.ts

Fixes: https://github.com/redhat-developer/yaml-language-server/issues/162
Tests will need to be updated after https://github.com/redhat-developer/yaml-language-server/pull/160 is merged

Fixed offset undefined error

---

src/languageservice/parser/jsonParser07.ts
src/languageservice/parser/yamlParser07.ts
src/languageservice/services/yamlValidation.ts
test/schema.test.ts

This fix adds in the custom json oneOf comparator that is present in the json schema 4 parser

Port the custom kubernetes oneOf comparator from json schema 4 parser

---

src/languageservice/services/yamlCompletion.ts
src/languageservice/utils/json.ts
test/defaultSnippets.test.ts
test/fixtures/defaultSnippets.json

This PR fixes some outstanding issues with default snippets. Default snippets still isn't perfect but its getting closer.
Fix for https://github.com/redhat-developer/yaml-language-server/issues/225.

Fixed issue with arrays in default snippets

---

ploparraymax.yaml
src/languageservice/services/yamlCompletion.ts
test/autoCompletion.maxproperties.test.ts
test/fixtures/testArrayMaxProperties.json

PR to show which cases would be nice to be supported

Avoid providing completion when "maxProperties" is reached #269

---

CHANGELOG.md
package.json

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

Update to 0.9.0

---

src/languageservice/services/schemaRequestHandler.ts

Removes the telemetry call that is not used or needed.

Removes left over telemetry call

---

.github/workflows/CI.yaml
.gitignore
.prettierrc.json
.travis.yml
package.json

It is simple Action to build each PR across all OS.

Add GH Actions workflow to build PR

---

src/languageservice/jsonSchema.ts
src/languageservice/parser/jsonParser07.ts
src/languageservice/services/yamlCompletion.ts
src/languageservice/services/yamlSchemaService.ts
src/languageservice/utils/json.ts
src/languageservice/utils/objects.ts
src/languageservice/yamlLanguageService.ts
src/server.ts
test/defaultSnippets.test.ts
tsconfig.json

This PR will do 2 things. 
1. alphabetize the `tsconfig` so that it is easier to compare and find things in it.
2. update all `tslint:disable` lines to `eslint-disable` syntax

Update eslint-disable syntax

---

src/languageservice/services/yamlCompletion.ts
src/languageservice/services/yamlHover.ts
src/languageservice/services/yamlSchemaService.ts
src/languageservice/services/yamlValidation.ts

Fix warnings in 'services'

---

test/autoCompletion.test.ts
test/customTags.test.ts
test/defaultSnippets.test.ts
test/documentSymbols.test.ts
test/findDefintion.test.ts
test/formatter.test.ts
test/hover.test.ts
test/integration.test.ts
test/jsonParser.test.ts
test/mulipleDocuments.test.ts
test/schema.test.ts
test/schemaValidation.test.ts
test/utils/serviceSetup.ts
test/utils/testHelper.ts
test/utils/verifyError.ts

Fix all eslint warnings in tests

---

src/languageservice/services/yamlSchemaService.ts

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

Fix grammar in message log

---

CHANGELOG.md
package.json

This is a bug fix release that includes the fix for cannot read property 'lineComments' of undefined Code: -32603

Update to 0.10.1

---

CHANGELOG.md
README.md
package.json

Signed-off-by: Yevhen Vydolob <yvydolob@redhat.com>

Release '0.11.0'

---

src/languageservice/services/yamlFormatter.ts
test/formatter.test.ts

Fix formatting to use tabWidth option again

---

CHANGELOG.md
package.json

Bug fix release, to provide fix for https://github.com/redhat-developer/vscode-yaml/issues/366

Release '0.11.1'

---

src/languageservice/services/yamlCompletion.ts
test/autoCompletion.test.ts

Fix error if schema doesn't contain type

---

.github/ISSUE_TEMPLATE/a_question.md
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement.md
.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

These are just some simple issue/pull request templates that will make it easier for users to file enhancements/bugs/questions.
Once these are merged here I'll make a PR for them in vscode-yaml

Add in issue and pull request templates

---

src/requestTypes.ts
src/server.ts

This PR is the server side part to https://github.com/redhat-developer/vscode-yaml/pull/388
https://github.com/redhat-developer/vscode-yaml/issues/387
Follow test instructions in: https://github.com/redhat-developer/vscode-yaml/pull/388

Allow array for fileMatch in yamlValidation contribution

---

CHANGELOG.md
package.json

Change version to `0.13.0` and add changelog section

Release '0.13.0'

---

test/schemaValidation.test.ts

Adds a test for the reference-uri schema validation
related to #181

add tests for reference-uri schemas

---

.github/workflows/CI.yaml
.github/workflows/release.yaml
README.md

This PR tacks onto https://github.com/redhat-developer/yaml-language-server/pull/367 and update the readme with info about the containerized language server. It also updates both CI jobs. Now `next` images will be produced on each pull request merge. Also, on release new `latest` and versioned images will be created.
https://github.com/redhat-developer/yaml-language-server/pull/367

Update release ci and README with containerized language server info

---

CHANGELOG.md
package.json

Release '0.14.0'

---

src/languageservice/services/yamlFolding.ts
test/yamlFolding.test.ts

Fixes folding ranges computation
Fix #400 and https://github.com/redhat-developer/vscode-yaml/issues/422
Added test from samples provided in issues

Fix folding

---

.vscode/launch.json
package.json
src/languageservice/services/yamlFolding.ts
test/arrUtils.test.ts
test/autoCompletion.test.ts
test/customTags.test.ts
test/defaultSnippets.test.ts
test/documentPositionCalculator.test.ts
test/documentSymbols.test.ts
test/findLinks.test.ts
test/formatter.test.ts
test/hover.test.ts
test/integration.test.ts
test/jsonParser.test.ts
test/multipleDocuments.test.ts
test/objects.test.ts
test/paths.test.ts
test/schema.test.ts
test/schemaRequestHandler.test.ts
test/schemaValidation.test.ts
test/strings.test.ts
test/textBuffer.test.ts
test/yamlFolding.test.ts
test/yamlOnTypeFormatting.test.ts
test/yamlParser.test.ts
test/yamlSchema.test.ts

Update all test to use mocha bdd test interface
#398
all test should pass

Use mocha bdd interface for all tests

---

CHANGELOG.md
README.md
package.json

Release '0.15.0'

---

package.json
test/documentSymbols.test.ts
test/utils/verifyError.ts
yarn.lock

Upgrade to `vscode-json-languageservice@4.0.2`
Fix: #405
With tests and manually

Upgrade to newer vscode-json-languageservice

---

src/languageservice/services/yamlCompletion.ts
test/autoCompletion.test.ts

Signed-off-by: Yevhen Vydolob <yvydolob@redhat.com>
Fix object indentation in array snippet.
Demo:
https://github.com/redhat-developer/vscode-yaml/issues/432
With unit test

Fix indentation for object in array

---

src/languageservice/services/yamlCompletion.ts
test/autoCompletion.test.ts

Add quotation to object key if it start with '@'
https://user-images.githubusercontent.com/929743/114019434-12456500-9877-11eb-8598-af6cbd2edbdf.mov
Fix https://github.com/redhat-developer/vscode-yaml/issues/439
With test and manually, use schema provided in https://github.com/redhat-developer/vscode-yaml/issues/439

 Add quotation to object key if it start with '@'

---

.vscode/tasks.json
test/defaultSnippets.test.ts

Fix test names

---

CHANGELOG.md
package.json

Release '0.19.0'

---

.vscode/tasks.json
src/languageserver/handlers/settingsHandlers.ts
src/languageservice/parser/custom-tag-provider.ts
src/languageservice/parser/yaml-documents.ts
src/languageservice/parser/yamlParser07.ts
src/languageservice/services/yamlValidation.ts
src/languageservice/yamlLanguageService.ts
src/yamlSettings.ts
test/utils/serviceSetup.ts
test/yaml-documents.test.ts
test/yamlParser.test.ts

This PR add option for default yaml version.

Add preference option for yaml version

---

.vscode/tasks.json
src/languageserver/handlers/settingsHandlers.ts
src/languageserver/telemetry.ts
src/languageservice/services/yamlCompletion.ts
src/languageservice/utils/schemaUrls.ts
src/languageservice/yamlLanguageService.ts
src/yamlServerInit.ts
test/settingsHandlers.test.ts
test/telemetry.test.ts

Add telemetry notification.
It log errors happened during codecompetion computation and also log if user has `kubernetes` shema mapping.
Resolve #439

Add telemetry notification

---

test/schemaValidation.test.ts

Fix schema validation test

---

.github/workflows/default-branch-migration.yml

Add GH Actions workflow which start migrating default branch to `main` see https://github.com/marketplace/actions/default-branch-migration
#472

Add GH Action for default branch migration

---

package.json
test/schemaValidation.test.ts
yarn.lock

Upgrade yaml parser to latest version and fix one more test

Upgrade yaml parser to latest version

---

src/languageservice/services/schemaRequestHandler.ts
src/languageservice/services/yamlCommands.ts
test/schemaRequestHandler.test.ts
test/yamlCommands.test.ts

Fix opening local schema on windows with codelens.
Fix https://github.com/redhat-developer/vscode-yaml/issues/513
with unit test

Fix opening local schema on windows

---

package.json
yarn.lock

Upgrade yaml parser to latest version and fix one more test
NA
Tested using `yarn test` after version upgrade

Upgrade jsonc-parser to latest version

---

src/languageservice/services/yamlHover.ts
test/hover.test.ts
test/integration.test.ts
test/multipleDocuments.test.ts

Improve hover, according to #480 :
Resolve: #480
With tests

Improve hover

---

src/languageservice/services/yamlSchemaService.ts
test/autoCompletion.test.ts
test/yamlSchemaService.test.ts

Fixes inline schema URL handling.
Fix: https://github.com/redhat-developer/vscode-yaml/issues/550
with test

Fix inline schema with url handling

---

src/languageservice/parser/jsonParser07.ts
src/languageservice/utils/objects.ts
test/schemaValidation.test.ts

UnhandledPromiseRejection in jsonParser
Fix: #494
with tests

UnhandledPromiseRejection in jsonParser

---

.github/CODEOWNERS

Remove @joshuawilson from code owners

Remove joshuawilson from code owners

---

.vscode/launch.json
src/languageserver/handlers/settingsHandlers.ts
src/languageservice/jsonASTTypes.ts
src/languageservice/parser/ast-converter.ts
src/languageservice/parser/json-schema07-validator.ts
src/languageservice/parser/yaml-documents.ts
src/languageservice/services/yamlCompletion.ts
src/languageservice/services/yamlValidation.ts
src/languageservice/utils/arrUtils.ts
src/languageservice/utils/astUtils.ts
src/languageservice/utils/strings.ts
src/languageservice/utils/textBuffer.ts
src/languageservice/yamlLanguageService.ts
test/astUtils.test.ts
test/autoCompletion.test.ts
test/defaultSnippets.test.ts
test/yaml-documents.test.ts
test/yamlSchemaService.test.ts

This PR add usage of new AST for code completion, now code completion uses raw AST(without converting it to JSON compatible AST)  
Basically it is not completely rewrite, it is a port of old code completion to new AST. 
Also to be able select proper JSON Schema I port validation code to new AST(`json-schema07-validator.ts`).
So we can remove AST convert completely( delete `ast-converter.ts` and all related code/types).
Resolve #517
With tests

New completion

---

CHANGELOG.md

A bug fix release, to fix https://github.com/redhat-developer/yaml-language-server/pull/576

Release '1.1.1'

---

src/languageservice/parser/yaml-documents.ts
src/languageservice/services/yamlCompletion.ts
src/languageservice/utils/astUtils.ts
test/astUtils.test.ts
test/autoCompletion.test.ts
test/autoCompletionFix.test.ts
test/fixtures/test-nested-object-array.json
test/yaml-documents.test.ts

Fix code completion for nested objects in array
Fix: https://github.com/redhat-developer/vscode-yaml/issues/621
with tests

Fix code completion for nested objects in array

---

CHANGELOG.md

Release '1.2.2'

---

src/languageservice/services/yamlCompletion.ts
test/autoCompletion.test.ts
test/autoCompletionFix.test.ts
test/fixtures/test-completion-oneOf.json

Fix code completion for 'anyOf' schemas
Fix: https://github.com/redhat-developer/yaml-language-server/issues/563
with test

Fix code completion for 'anyOf' schemas

---

src/languageservice/services/yamlCompletion.ts
test/autoCompletion.test.ts

Fix completion of properties if maxProperties is set and last allowed property is reached.
#612 
Added test for completion after beginning to type the last allowed property.

Fix completion of last property when maxProperties is set

---

package.json
yarn.lock

update coveralls and add scripts to coverage excludes
Signed-off-by: Gorkem Ercan <gorkem.ercan@gmail.com>
Runs the current test set sucessfully

update coveralls dependency

---

.github/CODEOWNERS

Remove jpinkney from codeowners

---

package.json
test/autoCompletion.test.ts
tsconfig.json
yarn.lock

The latest version of request-lib version 0.5.6 integrated. This version contains the proxy support
https://github.com/redhat-developer/yaml-language-server/issues/588
Yes with test cases

Fix proxy environment and settings not honored

---

src/languageserver/handlers/settingsHandlers.ts
src/requestTypes.ts
src/yamlSettings.ts
test/settingsHandlers.test.ts

https://user-images.githubusercontent.com/93245779/147567212-77383a76-bdfb-4701-b4fd-3bf9fbf0b99c.mp4
https://github.com/redhat-developer/vscode-yaml/issues/573
Yes. with test case

when detect Indentation is false set the editior.tabSize based on settings value

---

src/languageservice/parser/ast-converter.ts
src/languageservice/parser/jsonParser07.ts
src/languageservice/services/yamlCompletion.ts
src/languageservice/services/yamlValidation.ts
src/languageservice/utils/arrUtils.ts
src/languageservice/yamlLanguageService.ts
src/server.ts
src/webworker/yamlServerMain.ts
src/yamlServerInit.ts
test/hover.test.ts
test/schemaValidation.test.ts
test/utils/testHelper.ts
test/utils/testsTypes.ts

It provided fixes for error reported by telemetry, like https://github.com/redhat-developer/vscode-yaml/issues/653 and https://github.com/redhat-developer/vscode-yaml/issues/651
Also it fixes `TypeError: Cannot read property 'offset' of undefined`,
`TypeError: e.indexOf is not a function at w` and `TypeError: Cannot read property 'type' of undefined`
Fix: https://github.com/redhat-developer/vscode-yaml/issues/653
Fix: https://github.com/redhat-developer/vscode-yaml/issues/651
with tests

Fix errors reported by telemetry

---

src/languageservice/parser/yaml-documents.ts
src/languageservice/parser/yamlParser07.ts
test/documentSymbols.test.ts
test/hover.test.ts

This PR related to show the hover on the property when the next line is empty/null value
https://github.com/redhat-developer/yaml-language-server/issues/615
Yes. With test cases

changed parser when last line is empty or null

---

README.md

MoreInfo: <https://github.com/jayli/vim-easycomplete>
Update README.md. Add vim-easycomplete support.

doc: add vim-easycomplete support for yaml-lsp

---

src/languageservice/parser/yaml-documents.ts
src/languageservice/services/yamlCompletion.ts
test/autoCompletion.test.ts
test/yaml-documents.test.ts

This PR provides valid suggestion from schema even though the list indentation not in a proper level
https://github.com/redhat-developer/yaml-language-server/issues/646
Yes with UT

fixed auto completion provides valid suggetion even though list indentation not proper

---

src/languageservice/parser/jsonParser07.ts
test/schemaValidation.test.ts

Reverts redhat-developer/yaml-language-server#663
Time being will revert this code and working on the issue

Revert "Schema validation should check the object's oneOf if it has instead of the object type"

---

src/languageservice/parser/ast-converter.ts
src/languageservice/parser/jsonParser07.ts
test/schemaValidation.test.ts

This PR checks on the missing property validation that the expected property is undefined or not instead of null
https://github.com/redhat-developer/yaml-language-server/issues/665
Yes, added UT for this scenario

changed on specific to undefined check instead of null and undefined check

---

src/languageservice/parser/jsonParser07.ts
test/schemaValidation.test.ts

This PR showing the opt matched errors while validating the YAML
https://github.com/redhat-developer/vscode-yaml/issues/692
https://github.com/redhat-developer/vscode-yaml/issues/708
Yes added UT and tested all the mentioned scenario

changed comparison logic on result match while showing error

---

package.json
yarn.lock

Update the YAML parser to pickup fixes.
fixes https://github.com/redhat-developer/vscode-yaml/issues/712
Existing unit tests

update parser to 2.0.0-11

---

src/languageservice/services/yamlSchemaService.ts

Make no content error more informative

---

src/languageserver/handlers/notificationHandlers.ts

remove tracing

---

package.json
yarn.lock

Updates mocha to resolve a security warning.

Update mocha to 9.2.2

---

CHANGELOG.md
yarn.lock

release 1.8.0

---

package.json

bump version to 1.9.0
no Ref
NA

bump 1.9.0

---

src/languageservice/parser/jsonParser07.ts
src/languageservice/services/yamlHover.ts
test/hover.test.ts

This PR refers to show the schema description while hover on the ref node
https://github.com/redhat-developer/yaml-language-server/issues/737
Yes, added UT

hover on the reference node

---

CHANGELOG.md

release 1.9.0

---

package.json

bump version 1.10.0
no ref.
NA

updated bump version 1.10.0

---

package.json

bump version 1.11.0

---

src/languageservice/services/yamlValidation.ts

It fix error event which we send on validation errors
Fix: https://github.com/redhat-developer/vscode-yaml/issues/816

fix: fix validation telemetry error event

---

src/languageservice/utils/schemaUtils.ts
test/yamlCodeLens.test.ts

This fix shows the description on root of the document.
https://github.com/redhat-developer/vscode-yaml/issues/809
Yes. added UT

showed the description on root of the document

---

src/languageservice/services/yamlCompletion.ts
test/autoCompletion.test.ts

This PR should suggest all matching combination values when auto completion
https://github.com/redhat-developer/yaml-language-server/issues/769
Yes added UT

added child label value to parent label if parent label undefined

---

test/schemaValidation.test.ts

This PR will resolve the test case failure as per new git-workflow.json
https://github.com/SchemaStore/schemastore/pull/2510
Updated existing UT

changed test case scenorio based on the new git-workflow.json

---

src/languageservice/services/yamlCompletion.ts
test/autoCompletion.test.ts

This PR added quotes if the key is 'null'
https://github.com/redhat-developer/vscode-yaml/issues/842
Yes added UT.

added quotes for null key during completion

---

.github/workflows/CI.yaml
.gitignore
package.json
yarn.lock

Creates sarif output from build and uploads to GitHub interface
N/A
It is a CI change

Upload sarif output

---

src/languageserver/handlers/schemaSelectionHandlers.ts
src/languageservice/parser/jsonParser07.ts
src/languageservice/services/yamlCompletion.ts
src/languageservice/services/yamlOnTypeFormatting.ts
src/languageservice/utils/astUtils.ts
src/languageservice/utils/indentationGuesser.ts
src/languageservice/utils/schemaUrls.ts
src/languageservice/utils/schemaUtils.ts
test/utils/verifyError.ts

Cleans up some unused code, extra returns

Some code cleanup

---

CHANGELOG.md

Release vscode-yaml v1.11.0
NA
NA

updated changelog.md for release 1.11.0

---

package.json

bump 1.12.0

---

package.json
yarn.lock

Updates the yaml parser dependency to version 2.2.1
N/A
Existing tests

update to yaml parser 2.2.1

---

src/requestTypes.ts

Replaces {} types with unknowns.
Fixes the eslint linter issues

Fixes ban type lint errors

---

src/webworker/yamlServerMain.ts

change {} to unknown 
fixes linter issues
Existing tests

Fix banned type lint error for YamlServerMain.ts

---

src/languageserver/handlers/validationHandlers.ts
src/languageservice/utils/arrUtils.ts

Removes the any reference and uses generics to define the API.
Fixes a couple of eslint warnings
Existing test

Removes any reference from API

---

src/languageservice/utils/schemaUtils.ts
test/schemaValidation.test.ts

This PR shows schema type when mismatch error than its title
https://github.com/redhat-developer/yaml-language-server/issues/845
Yes. Updated existing UT

provide preference on schema type than its title

---

CHANGELOG.md

Update for new release
no ref
NA

updated changelog.md for new release

---

package.json

bump version to 1.13.0
no ref
NA

bump version 1.13.0

---

src/yamlSettings.ts

Fixes the default value for keyOrder setting
Existing tests

fix the default for keyorder

---

README.md

remove TravisCIi status from README

Remove Travis CI status

---

CHANGELOG.md

updated changelog.md for release 1.13.0

---

package.json

bump YAML LS 1.14.0

---

src/languageservice/services/yamlHover.ts

Changes regex to be more deterministic. I can not reproduce the error reported on #874 with a test but I think this will potentially fix it.
#874 
Existing test set should pass with this change

Change the regex on hover

---

.github/workflows/CI.yaml

Pins the versions of all actions. Adds
the minimum required permissions.
Build changes

Pin versions and add permissions

---

src/languageservice/services/yamlHover.ts

Enhanced how examples are being parsed as a plain string 
#889

fix: add indentation when parsing example as string

---

src/languageservice/parser/ast-converter.ts
test/yamlParser.test.ts

Adds a check to skip AST conversion if a circular Alias is encountered.
- fixes #897
A new unit test added to parser tests

Handle circular aliasases

---

CHANGELOG.md

updated changelog for release 1.14.0

---

src/languageservice/parser/yamlParser07.ts
src/languageservice/services/documentSymbols.ts
src/languageservice/services/modelineUtil.ts
src/languageservice/services/yamlFormatter.ts
src/languageservice/services/yamlHover.ts
src/languageservice/services/yamlSchemaService.ts
src/languageservice/services/yamlValidation.ts
src/languageservice/utils/documentPositionCalculator.ts
src/languageservice/utils/objects.ts
src/languageservice/utils/strings.ts
src/server.ts
test/schema.test.ts

This removes all `'use strict'` directives. TypeScript adds this for us.
N/A
Inspect the output.

Remove 'use strict'

---

package.json

bump version 1.16.0

---

package.json
yarn.lock

Bump v1.17.0 as v1.16.0 released
NA
NA

bump v.1.7.0

---

package.json

Changed author and contributors name of the extension
NA
NA

changed author and contributors name

---

.github/workflows/release.yaml

Support linux/arm64 docker image
https://github.com/redhat-developer/yaml-language-server/issues/997
NA

supported docker arm64 image

---

CHANGELOG.md

Changelog updated for the release v1.17.0
NA
NA

changelog updated for the release v1.17.0

---

test/autoCompletion.test.ts
test/defaultSnippets.test.ts
test/documentSymbols.test.ts
test/findLinks.test.ts
test/jsonParser.test.ts
test/schema.test.ts
test/schemaRequestHandler.test.ts

Fixed test case lint issues
https://github.com/redhat-developer/yaml-language-server/issues/1018
Yes. With existing test cases

Fixed test lint issues

---

src/languageservice/services/yamlSchemaService.ts
test/schemaValidation.test.ts

This PR will decoded the URI component values on ref value
https://github.com/redhat-developer/vscode-yaml/issues/1082
Added test case

Decoded URI component on ref value

---

package.json

Bump v1.18.0

---

src/languageservice/jsonASTTypes.ts
src/languageservice/parser/ast-converter.ts
src/languageservice/parser/jsonParser07.ts
src/languageservice/services/yamlCompletion.ts
src/languageservice/yamlLanguageService.ts
test/autoCompletionFix.test.ts

This PR suggests ENUM values based on type. Especially on the YAML spec 1.1 Boolean values like `on,off,true,false,yes,no`
https://github.com/redhat-developer/yaml-language-server/issues/1036
Yes. Added test cases

Fix ENUM yes no values

---

package.json

Bump version to 1.19.0
No Ref
NA

bump version to 1.19.0

---

.github/workflows/release.yaml

Try to check if `NODE_AUTH_TOKEN` is available or not
NA
NA

check NODE_AUTH_TOKEN is available or not

---

.github/workflows/CI.yaml

Reverts redhat-developer/yaml-language-server#1101

Revert "Update CI.yaml"

---

.github/workflows/CI.yaml
.github/workflows/release.yaml

Setup `.npmrc` on the npm auth for publish
NPM publish auth failed
NA

set .npmrc

---

package-lock.json
package.json

Upversion to 1.20.0
Existing tests (there's no code changes in this PR)

Upversion to 1.20.0

---

src/languageserver/handlers/settingsHandlers.ts

Adds support for `yaml-textmate` and `yaml-tmlanguage` languages
* https://github.com/redhat-developer/vscode-yaml/issues/1092
* https://github.com/redhat-developer/vscode-yaml/pull/1093

Support `yaml-textmate` and `yaml-tmlanguage` languages
